/*
 * Forgejo API
 * This documentation describes the Forgejo API.
 *
 * The version of the OpenAPI document: 14.0.2-24-ea4f733de8+gitea-1.22.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.smithyai.forgejoclient.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import dev.smithyai.forgejoclient.model.CommitDateOptions;
import dev.smithyai.forgejoclient.model.Identity;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for DeleteFileOptions
 */
public class DeleteFileOptionsTest {
    private final DeleteFileOptions model = new DeleteFileOptions();

    /**
     * Model tests for DeleteFileOptions
     */
    @Test
    public void testDeleteFileOptions() {
        // TODO: test DeleteFileOptions
    }

    /**
     * Test the property 'author'
     */
    @Test
    public void authorTest() {
        // TODO: test author
    }

    /**
     * Test the property 'branch'
     */
    @Test
    public void branchTest() {
        // TODO: test branch
    }

    /**
     * Test the property 'committer'
     */
    @Test
    public void committerTest() {
        // TODO: test committer
    }

    /**
     * Test the property 'dates'
     */
    @Test
    public void datesTest() {
        // TODO: test dates
    }

    /**
     * Test the property 'message'
     */
    @Test
    public void messageTest() {
        // TODO: test message
    }

    /**
     * Test the property 'newBranch'
     */
    @Test
    public void newBranchTest() {
        // TODO: test newBranch
    }

    /**
     * Test the property 'sha'
     */
    @Test
    public void shaTest() {
        // TODO: test sha
    }

    /**
     * Test the property 'signoff'
     */
    @Test
    public void signoffTest() {
        // TODO: test signoff
    }

}
