/*
 * Forgejo API
 * This documentation describes the Forgejo API.
 *
 * The version of the OpenAPI document: 14.0.2-24-ea4f733de8+gitea-1.22.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.smithyai.forgejoclient.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for EditReleaseOption
 */
public class EditReleaseOptionTest {
    private final EditReleaseOption model = new EditReleaseOption();

    /**
     * Model tests for EditReleaseOption
     */
    @Test
    public void testEditReleaseOption() {
        // TODO: test EditReleaseOption
    }

    /**
     * Test the property 'body'
     */
    @Test
    public void bodyTest() {
        // TODO: test body
    }

    /**
     * Test the property 'draft'
     */
    @Test
    public void draftTest() {
        // TODO: test draft
    }

    /**
     * Test the property 'hideArchiveLinks'
     */
    @Test
    public void hideArchiveLinksTest() {
        // TODO: test hideArchiveLinks
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'prerelease'
     */
    @Test
    public void prereleaseTest() {
        // TODO: test prerelease
    }

    /**
     * Test the property 'tagName'
     */
    @Test
    public void tagNameTest() {
        // TODO: test tagName
    }

    /**
     * Test the property 'targetCommitish'
     */
    @Test
    public void targetCommitishTest() {
        // TODO: test targetCommitish
    }

}
