/*
 * Forgejo API
 * This documentation describes the Forgejo API.
 *
 * The version of the OpenAPI document: 14.0.2-24-ea4f733de8+gitea-1.22.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.smithyai.forgejoclient.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for GeneralRepoSettings
 */
public class GeneralRepoSettingsTest {
    private final GeneralRepoSettings model = new GeneralRepoSettings();

    /**
     * Model tests for GeneralRepoSettings
     */
    @Test
    public void testGeneralRepoSettings() {
        // TODO: test GeneralRepoSettings
    }

    /**
     * Test the property 'forksDisabled'
     */
    @Test
    public void forksDisabledTest() {
        // TODO: test forksDisabled
    }

    /**
     * Test the property 'httpGitDisabled'
     */
    @Test
    public void httpGitDisabledTest() {
        // TODO: test httpGitDisabled
    }

    /**
     * Test the property 'lfsDisabled'
     */
    @Test
    public void lfsDisabledTest() {
        // TODO: test lfsDisabled
    }

    /**
     * Test the property 'migrationsDisabled'
     */
    @Test
    public void migrationsDisabledTest() {
        // TODO: test migrationsDisabled
    }

    /**
     * Test the property 'mirrorsDisabled'
     */
    @Test
    public void mirrorsDisabledTest() {
        // TODO: test mirrorsDisabled
    }

    /**
     * Test the property 'starsDisabled'
     */
    @Test
    public void starsDisabledTest() {
        // TODO: test starsDisabled
    }

    /**
     * Test the property 'timeTrackingDisabled'
     */
    @Test
    public void timeTrackingDisabledTest() {
        // TODO: test timeTrackingDisabled
    }

}
