/*
 * Forgejo API
 * This documentation describes the Forgejo API.
 *
 * The version of the OpenAPI document: 14.0.2-24-ea4f733de8+gitea-1.22.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.smithyai.forgejoclient.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for NotificationCount
 */
public class NotificationCountTest {
    private final NotificationCount model = new NotificationCount();

    /**
     * Model tests for NotificationCount
     */
    @Test
    public void testNotificationCount() {
        // TODO: test NotificationCount
    }

    /**
     * Test the property '_new'
     */
    @Test
    public void _newTest() {
        // TODO: test _new
    }

}
