/*
 * Forgejo API
 * This documentation describes the Forgejo API.
 *
 * The version of the OpenAPI document: 14.0.2-24-ea4f733de8+gitea-1.22.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.smithyai.forgejoclient.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for PackageFile
 */
public class PackageFileTest {
    private final PackageFile model = new PackageFile();

    /**
     * Model tests for PackageFile
     */
    @Test
    public void testPackageFile() {
        // TODO: test PackageFile
    }

    /**
     * Test the property 'size'
     */
    @Test
    public void sizeTest() {
        // TODO: test size
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'md5'
     */
    @Test
    public void md5Test() {
        // TODO: test md5
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'sha1'
     */
    @Test
    public void sha1Test() {
        // TODO: test sha1
    }

    /**
     * Test the property 'sha256'
     */
    @Test
    public void sha256Test() {
        // TODO: test sha256
    }

    /**
     * Test the property 'sha512'
     */
    @Test
    public void sha512Test() {
        // TODO: test sha512
    }

}
