/*
 * Forgejo API
 * This documentation describes the Forgejo API.
 *
 * The version of the OpenAPI document: 14.0.2-24-ea4f733de8+gitea-1.22.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.smithyai.forgejoclient.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import dev.smithyai.forgejoclient.model.Label;
import dev.smithyai.forgejoclient.model.Milestone;
import dev.smithyai.forgejoclient.model.PRBranchInfo;
import dev.smithyai.forgejoclient.model.Team;
import dev.smithyai.forgejoclient.model.User;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for PullRequest
 */
public class PullRequestTest {
    private final PullRequest model = new PullRequest();

    /**
     * Model tests for PullRequest
     */
    @Test
    public void testPullRequest() {
        // TODO: test PullRequest
    }

    /**
     * Test the property 'additions'
     */
    @Test
    public void additionsTest() {
        // TODO: test additions
    }

    /**
     * Test the property 'allowMaintainerEdit'
     */
    @Test
    public void allowMaintainerEditTest() {
        // TODO: test allowMaintainerEdit
    }

    /**
     * Test the property 'assignee'
     */
    @Test
    public void assigneeTest() {
        // TODO: test assignee
    }

    /**
     * Test the property 'assignees'
     */
    @Test
    public void assigneesTest() {
        // TODO: test assignees
    }

    /**
     * Test the property 'base'
     */
    @Test
    public void baseTest() {
        // TODO: test base
    }

    /**
     * Test the property 'body'
     */
    @Test
    public void bodyTest() {
        // TODO: test body
    }

    /**
     * Test the property 'changedFiles'
     */
    @Test
    public void changedFilesTest() {
        // TODO: test changedFiles
    }

    /**
     * Test the property 'closedAt'
     */
    @Test
    public void closedAtTest() {
        // TODO: test closedAt
    }

    /**
     * Test the property 'comments'
     */
    @Test
    public void commentsTest() {
        // TODO: test comments
    }

    /**
     * Test the property 'createdAt'
     */
    @Test
    public void createdAtTest() {
        // TODO: test createdAt
    }

    /**
     * Test the property 'deletions'
     */
    @Test
    public void deletionsTest() {
        // TODO: test deletions
    }

    /**
     * Test the property 'diffUrl'
     */
    @Test
    public void diffUrlTest() {
        // TODO: test diffUrl
    }

    /**
     * Test the property 'draft'
     */
    @Test
    public void draftTest() {
        // TODO: test draft
    }

    /**
     * Test the property 'dueDate'
     */
    @Test
    public void dueDateTest() {
        // TODO: test dueDate
    }

    /**
     * Test the property 'flow'
     */
    @Test
    public void flowTest() {
        // TODO: test flow
    }

    /**
     * Test the property 'head'
     */
    @Test
    public void headTest() {
        // TODO: test head
    }

    /**
     * Test the property 'htmlUrl'
     */
    @Test
    public void htmlUrlTest() {
        // TODO: test htmlUrl
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'isLocked'
     */
    @Test
    public void isLockedTest() {
        // TODO: test isLocked
    }

    /**
     * Test the property 'labels'
     */
    @Test
    public void labelsTest() {
        // TODO: test labels
    }

    /**
     * Test the property 'mergeBase'
     */
    @Test
    public void mergeBaseTest() {
        // TODO: test mergeBase
    }

    /**
     * Test the property 'mergeCommitSha'
     */
    @Test
    public void mergeCommitShaTest() {
        // TODO: test mergeCommitSha
    }

    /**
     * Test the property 'mergeable'
     */
    @Test
    public void mergeableTest() {
        // TODO: test mergeable
    }

    /**
     * Test the property 'merged'
     */
    @Test
    public void mergedTest() {
        // TODO: test merged
    }

    /**
     * Test the property 'mergedAt'
     */
    @Test
    public void mergedAtTest() {
        // TODO: test mergedAt
    }

    /**
     * Test the property 'mergedBy'
     */
    @Test
    public void mergedByTest() {
        // TODO: test mergedBy
    }

    /**
     * Test the property 'milestone'
     */
    @Test
    public void milestoneTest() {
        // TODO: test milestone
    }

    /**
     * Test the property 'number'
     */
    @Test
    public void numberTest() {
        // TODO: test number
    }

    /**
     * Test the property 'patchUrl'
     */
    @Test
    public void patchUrlTest() {
        // TODO: test patchUrl
    }

    /**
     * Test the property 'pinOrder'
     */
    @Test
    public void pinOrderTest() {
        // TODO: test pinOrder
    }

    /**
     * Test the property 'requestedReviewers'
     */
    @Test
    public void requestedReviewersTest() {
        // TODO: test requestedReviewers
    }

    /**
     * Test the property 'requestedReviewersTeams'
     */
    @Test
    public void requestedReviewersTeamsTest() {
        // TODO: test requestedReviewersTeams
    }

    /**
     * Test the property 'reviewComments'
     */
    @Test
    public void reviewCommentsTest() {
        // TODO: test reviewComments
    }

    /**
     * Test the property 'state'
     */
    @Test
    public void stateTest() {
        // TODO: test state
    }

    /**
     * Test the property 'title'
     */
    @Test
    public void titleTest() {
        // TODO: test title
    }

    /**
     * Test the property 'updatedAt'
     */
    @Test
    public void updatedAtTest() {
        // TODO: test updatedAt
    }

    /**
     * Test the property 'url'
     */
    @Test
    public void urlTest() {
        // TODO: test url
    }

    /**
     * Test the property 'user'
     */
    @Test
    public void userTest() {
        // TODO: test user
    }

}
