/*
 * Forgejo API
 * This documentation describes the Forgejo API.
 *
 * The version of the OpenAPI document: 14.0.2-24-ea4f733de8+gitea-1.22.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.smithyai.forgejoclient.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for PullRequestMeta
 */
public class PullRequestMetaTest {
    private final PullRequestMeta model = new PullRequestMeta();

    /**
     * Model tests for PullRequestMeta
     */
    @Test
    public void testPullRequestMeta() {
        // TODO: test PullRequestMeta
    }

    /**
     * Test the property 'draft'
     */
    @Test
    public void draftTest() {
        // TODO: test draft
    }

    /**
     * Test the property 'htmlUrl'
     */
    @Test
    public void htmlUrlTest() {
        // TODO: test htmlUrl
    }

    /**
     * Test the property 'merged'
     */
    @Test
    public void mergedTest() {
        // TODO: test merged
    }

    /**
     * Test the property 'mergedAt'
     */
    @Test
    public void mergedAtTest() {
        // TODO: test mergedAt
    }

}
