/*
 * Forgejo API
 * This documentation describes the Forgejo API.
 *
 * The version of the OpenAPI document: 14.0.2-24-ea4f733de8+gitea-1.22.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.smithyai.forgejoclient.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for UserSettingsOptions
 */
public class UserSettingsOptionsTest {
    private final UserSettingsOptions model = new UserSettingsOptions();

    /**
     * Model tests for UserSettingsOptions
     */
    @Test
    public void testUserSettingsOptions() {
        // TODO: test UserSettingsOptions
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'diffViewStyle'
     */
    @Test
    public void diffViewStyleTest() {
        // TODO: test diffViewStyle
    }

    /**
     * Test the property 'enableRepoUnitHints'
     */
    @Test
    public void enableRepoUnitHintsTest() {
        // TODO: test enableRepoUnitHints
    }

    /**
     * Test the property 'fullName'
     */
    @Test
    public void fullNameTest() {
        // TODO: test fullName
    }

    /**
     * Test the property 'hideActivity'
     */
    @Test
    public void hideActivityTest() {
        // TODO: test hideActivity
    }

    /**
     * Test the property 'hideEmail'
     */
    @Test
    public void hideEmailTest() {
        // TODO: test hideEmail
    }

    /**
     * Test the property 'hidePronouns'
     */
    @Test
    public void hidePronounsTest() {
        // TODO: test hidePronouns
    }

    /**
     * Test the property 'language'
     */
    @Test
    public void languageTest() {
        // TODO: test language
    }

    /**
     * Test the property 'location'
     */
    @Test
    public void locationTest() {
        // TODO: test location
    }

    /**
     * Test the property 'pronouns'
     */
    @Test
    public void pronounsTest() {
        // TODO: test pronouns
    }

    /**
     * Test the property 'theme'
     */
    @Test
    public void themeTest() {
        // TODO: test theme
    }

    /**
     * Test the property 'website'
     */
    @Test
    public void websiteTest() {
        // TODO: test website
    }

}
