/*
 * Forgejo API
 * This documentation describes the Forgejo API.
 *
 * The version of the OpenAPI document: 14.0.2-24-ea4f733de8+gitea-1.22.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.smithyai.forgejoclient.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import dev.smithyai.forgejoclient.model.WikiCommit;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for WikiPageMetaData
 */
public class WikiPageMetaDataTest {
    private final WikiPageMetaData model = new WikiPageMetaData();

    /**
     * Model tests for WikiPageMetaData
     */
    @Test
    public void testWikiPageMetaData() {
        // TODO: test WikiPageMetaData
    }

    /**
     * Test the property 'htmlUrl'
     */
    @Test
    public void htmlUrlTest() {
        // TODO: test htmlUrl
    }

    /**
     * Test the property 'lastCommit'
     */
    @Test
    public void lastCommitTest() {
        // TODO: test lastCommit
    }

    /**
     * Test the property 'subUrl'
     */
    @Test
    public void subUrlTest() {
        // TODO: test subUrl
    }

    /**
     * Test the property 'title'
     */
    @Test
    public void titleTest() {
        // TODO: test title
    }

}
