/*
 * Forgejo API
 * This documentation describes the Forgejo API.
 *
 * The version of the OpenAPI document: 14.0.2-24-ea4f733de8+gitea-1.22.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.smithyai.forgejoclient.api;

import dev.smithyai.forgejoclient.ApiException;
import dev.smithyai.forgejoclient.model.APINotFound;
import dev.smithyai.forgejoclient.model.APIValidationError;
import dev.smithyai.forgejoclient.model.GitignoreTemplateInfo;
import dev.smithyai.forgejoclient.model.LabelTemplate;
import dev.smithyai.forgejoclient.model.LicenseTemplateInfo;
import dev.smithyai.forgejoclient.model.LicensesTemplateListEntry;
import dev.smithyai.forgejoclient.model.MarkdownOption;
import dev.smithyai.forgejoclient.model.MarkupOption;
import dev.smithyai.forgejoclient.model.NodeInfo;
import dev.smithyai.forgejoclient.model.ServerVersion;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for MiscellaneousApi
 */
@Disabled
public class MiscellaneousApiTest {

    private final MiscellaneousApi api = new MiscellaneousApi();

    /**
     * Returns information about a gitignore template
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getGitignoreTemplateInfoTest() throws ApiException {
        String name = null;
        GitignoreTemplateInfo response = api.getGitignoreTemplateInfo(name);
        // TODO: test validations
    }

    /**
     * Returns all labels in a template
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getLabelTemplateInfoTest() throws ApiException {
        String name = null;
        List<LabelTemplate> response = api.getLabelTemplateInfo(name);
        // TODO: test validations
    }

    /**
     * Returns information about a license template
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getLicenseTemplateInfoTest() throws ApiException {
        String name = null;
        LicenseTemplateInfo response = api.getLicenseTemplateInfo(name);
        // TODO: test validations
    }

    /**
     * Returns the nodeinfo of the Forgejo application
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getNodeInfoTest() throws ApiException {
        NodeInfo response = api.getNodeInfo();
        // TODO: test validations
    }

    /**
     * Get default signing-key.ssh
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getSSHSigningKeyTest() throws ApiException {
        String response = api.getSSHSigningKey();
        // TODO: test validations
    }

    /**
     * Get default signing-key.gpg
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getSigningKeyTest() throws ApiException {
        String response = api.getSigningKey();
        // TODO: test validations
    }

    /**
     * Returns the version of the running application
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getVersionTest() throws ApiException {
        ServerVersion response = api.getVersion();
        // TODO: test validations
    }

    /**
     * Returns a list of all gitignore templates
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listGitignoresTemplatesTest() throws ApiException {
        List<String> response = api.listGitignoresTemplates();
        // TODO: test validations
    }

    /**
     * Returns a list of all label templates
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listLabelTemplatesTest() throws ApiException {
        List<String> response = api.listLabelTemplates();
        // TODO: test validations
    }

    /**
     * Returns a list of all license templates
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listLicenseTemplatesTest() throws ApiException {
        List<LicensesTemplateListEntry> response = api.listLicenseTemplates();
        // TODO: test validations
    }

    /**
     * Render a markdown document as HTML
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void renderMarkdownTest() throws ApiException {
        MarkdownOption body = null;
        String response = api.renderMarkdown(body);
        // TODO: test validations
    }

    /**
     * Render raw markdown as HTML
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void renderMarkdownRawTest() throws ApiException {
        String body = null;
        String response = api.renderMarkdownRaw(body);
        // TODO: test validations
    }

    /**
     * Render a markup document as HTML
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void renderMarkupTest() throws ApiException {
        MarkupOption body = null;
        String response = api.renderMarkup(body);
        // TODO: test validations
    }

}
