/*
 * Forgejo API
 * This documentation describes the Forgejo API.
 *
 * The version of the OpenAPI document: 14.0.2-24-ea4f733de8+gitea-1.22.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.smithyai.forgejoclient.api;

import dev.smithyai.forgejoclient.ApiException;
import dev.smithyai.forgejoclient.model.APINotFound;
import dev.smithyai.forgejoclient.model.ModelPackage;
import dev.smithyai.forgejoclient.model.PackageFile;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for PackageApi
 */
@Disabled
public class PackageApiTest {

    private final PackageApi api = new PackageApi();

    /**
     * Delete a package
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void deletePackageTest() throws ApiException {
        String owner = null;
        String type = null;
        String name = null;
        String version = null;
        api.deletePackage(owner, type, name, version);
        // TODO: test validations
    }

    /**
     * Gets a package
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getPackageTest() throws ApiException {
        String owner = null;
        String type = null;
        String name = null;
        String version = null;
        ModelPackage response = api.getPackage(owner, type, name, version);
        // TODO: test validations
    }

    /**
     * Link a package to a repository
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void linkPackageTest() throws ApiException {
        String owner = null;
        String type = null;
        String name = null;
        String repoName = null;
        api.linkPackage(owner, type, name, repoName);
        // TODO: test validations
    }

    /**
     * Gets all files of a package
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listPackageFilesTest() throws ApiException {
        String owner = null;
        String type = null;
        String name = null;
        String version = null;
        List<PackageFile> response = api.listPackageFiles(owner, type, name, version);
        // TODO: test validations
    }

    /**
     * Gets all packages of an owner
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listPackagesTest() throws ApiException {
        String owner = null;
        Integer page = null;
        Integer limit = null;
        String type = null;
        String q = null;
        List<ModelPackage> response = api.listPackages(owner, page, limit, type, q);
        // TODO: test validations
    }

    /**
     * Unlink a package from a repository
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void unlinkPackageTest() throws ApiException {
        String owner = null;
        String type = null;
        String name = null;
        api.unlinkPackage(owner, type, name);
        // TODO: test validations
    }

}
