/*
 * Forgejo API
 * This documentation describes the Forgejo API.
 *
 * The version of the OpenAPI document: 14.0.2-24-ea4f733de8+gitea-1.22.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.smithyai.forgejoclient.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import dev.smithyai.forgejoclient.model.AnnotatedTagObject;
import dev.smithyai.forgejoclient.model.CommitUser;
import dev.smithyai.forgejoclient.model.PayloadCommitVerification;
import dev.smithyai.forgejoclient.model.TagArchiveDownloadCount;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import dev.smithyai.forgejoclient.JSON;

/**
 * AnnotatedTag represents an annotated tag
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-03-07T21:26:32.673342+01:00[Europe/Amsterdam]", comments = "Generator version: 7.20.0")
public class AnnotatedTag {
  public static final String SERIALIZED_NAME_ARCHIVE_DOWNLOAD_COUNT = "archive_download_count";
  @SerializedName(SERIALIZED_NAME_ARCHIVE_DOWNLOAD_COUNT)
  @javax.annotation.Nullable
  private TagArchiveDownloadCount archiveDownloadCount;

  public static final String SERIALIZED_NAME_MESSAGE = "message";
  @SerializedName(SERIALIZED_NAME_MESSAGE)
  @javax.annotation.Nullable
  private String message;

  public static final String SERIALIZED_NAME_OBJECT = "object";
  @SerializedName(SERIALIZED_NAME_OBJECT)
  @javax.annotation.Nullable
  private AnnotatedTagObject _object;

  public static final String SERIALIZED_NAME_SHA = "sha";
  @SerializedName(SERIALIZED_NAME_SHA)
  @javax.annotation.Nullable
  private String sha;

  public static final String SERIALIZED_NAME_TAG = "tag";
  @SerializedName(SERIALIZED_NAME_TAG)
  @javax.annotation.Nullable
  private String tag;

  public static final String SERIALIZED_NAME_TAGGER = "tagger";
  @SerializedName(SERIALIZED_NAME_TAGGER)
  @javax.annotation.Nullable
  private CommitUser tagger;

  public static final String SERIALIZED_NAME_URL = "url";
  @SerializedName(SERIALIZED_NAME_URL)
  @javax.annotation.Nullable
  private String url;

  public static final String SERIALIZED_NAME_VERIFICATION = "verification";
  @SerializedName(SERIALIZED_NAME_VERIFICATION)
  @javax.annotation.Nullable
  private PayloadCommitVerification verification;

  public AnnotatedTag() {
  }

  public AnnotatedTag archiveDownloadCount(@javax.annotation.Nullable TagArchiveDownloadCount archiveDownloadCount) {
    this.archiveDownloadCount = archiveDownloadCount;
    return this;
  }

  /**
   * Get archiveDownloadCount
   * @return archiveDownloadCount
   */
  @javax.annotation.Nullable
  public TagArchiveDownloadCount getArchiveDownloadCount() {
    return archiveDownloadCount;
  }

  public void setArchiveDownloadCount(@javax.annotation.Nullable TagArchiveDownloadCount archiveDownloadCount) {
    this.archiveDownloadCount = archiveDownloadCount;
  }


  public AnnotatedTag message(@javax.annotation.Nullable String message) {
    this.message = message;
    return this;
  }

  /**
   * Get message
   * @return message
   */
  @javax.annotation.Nullable
  public String getMessage() {
    return message;
  }

  public void setMessage(@javax.annotation.Nullable String message) {
    this.message = message;
  }


  public AnnotatedTag _object(@javax.annotation.Nullable AnnotatedTagObject _object) {
    this._object = _object;
    return this;
  }

  /**
   * Get _object
   * @return _object
   */
  @javax.annotation.Nullable
  public AnnotatedTagObject getObject() {
    return _object;
  }

  public void setObject(@javax.annotation.Nullable AnnotatedTagObject _object) {
    this._object = _object;
  }


  public AnnotatedTag sha(@javax.annotation.Nullable String sha) {
    this.sha = sha;
    return this;
  }

  /**
   * Get sha
   * @return sha
   */
  @javax.annotation.Nullable
  public String getSha() {
    return sha;
  }

  public void setSha(@javax.annotation.Nullable String sha) {
    this.sha = sha;
  }


  public AnnotatedTag tag(@javax.annotation.Nullable String tag) {
    this.tag = tag;
    return this;
  }

  /**
   * Get tag
   * @return tag
   */
  @javax.annotation.Nullable
  public String getTag() {
    return tag;
  }

  public void setTag(@javax.annotation.Nullable String tag) {
    this.tag = tag;
  }


  public AnnotatedTag tagger(@javax.annotation.Nullable CommitUser tagger) {
    this.tagger = tagger;
    return this;
  }

  /**
   * Get tagger
   * @return tagger
   */
  @javax.annotation.Nullable
  public CommitUser getTagger() {
    return tagger;
  }

  public void setTagger(@javax.annotation.Nullable CommitUser tagger) {
    this.tagger = tagger;
  }


  public AnnotatedTag url(@javax.annotation.Nullable String url) {
    this.url = url;
    return this;
  }

  /**
   * Get url
   * @return url
   */
  @javax.annotation.Nullable
  public String getUrl() {
    return url;
  }

  public void setUrl(@javax.annotation.Nullable String url) {
    this.url = url;
  }


  public AnnotatedTag verification(@javax.annotation.Nullable PayloadCommitVerification verification) {
    this.verification = verification;
    return this;
  }

  /**
   * Get verification
   * @return verification
   */
  @javax.annotation.Nullable
  public PayloadCommitVerification getVerification() {
    return verification;
  }

  public void setVerification(@javax.annotation.Nullable PayloadCommitVerification verification) {
    this.verification = verification;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AnnotatedTag annotatedTag = (AnnotatedTag) o;
    return Objects.equals(this.archiveDownloadCount, annotatedTag.archiveDownloadCount) &&
        Objects.equals(this.message, annotatedTag.message) &&
        Objects.equals(this._object, annotatedTag._object) &&
        Objects.equals(this.sha, annotatedTag.sha) &&
        Objects.equals(this.tag, annotatedTag.tag) &&
        Objects.equals(this.tagger, annotatedTag.tagger) &&
        Objects.equals(this.url, annotatedTag.url) &&
        Objects.equals(this.verification, annotatedTag.verification);
  }

  @Override
  public int hashCode() {
    return Objects.hash(archiveDownloadCount, message, _object, sha, tag, tagger, url, verification);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AnnotatedTag {\n");
    sb.append("    archiveDownloadCount: ").append(toIndentedString(archiveDownloadCount)).append("\n");
    sb.append("    message: ").append(toIndentedString(message)).append("\n");
    sb.append("    _object: ").append(toIndentedString(_object)).append("\n");
    sb.append("    sha: ").append(toIndentedString(sha)).append("\n");
    sb.append("    tag: ").append(toIndentedString(tag)).append("\n");
    sb.append("    tagger: ").append(toIndentedString(tagger)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("    verification: ").append(toIndentedString(verification)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("archive_download_count", "message", "object", "sha", "tag", "tagger", "url", "verification"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to AnnotatedTag
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!AnnotatedTag.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in AnnotatedTag is not found in the empty JSON string", AnnotatedTag.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!AnnotatedTag.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `AnnotatedTag` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the optional field `archive_download_count`
      if (jsonObj.get("archive_download_count") != null && !jsonObj.get("archive_download_count").isJsonNull()) {
        TagArchiveDownloadCount.validateJsonElement(jsonObj.get("archive_download_count"));
      }
      if ((jsonObj.get("message") != null && !jsonObj.get("message").isJsonNull()) && !jsonObj.get("message").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `message` to be a primitive type in the JSON string but got `%s`", jsonObj.get("message").toString()));
      }
      // validate the optional field `object`
      if (jsonObj.get("object") != null && !jsonObj.get("object").isJsonNull()) {
        AnnotatedTagObject.validateJsonElement(jsonObj.get("object"));
      }
      if ((jsonObj.get("sha") != null && !jsonObj.get("sha").isJsonNull()) && !jsonObj.get("sha").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `sha` to be a primitive type in the JSON string but got `%s`", jsonObj.get("sha").toString()));
      }
      if ((jsonObj.get("tag") != null && !jsonObj.get("tag").isJsonNull()) && !jsonObj.get("tag").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `tag` to be a primitive type in the JSON string but got `%s`", jsonObj.get("tag").toString()));
      }
      // validate the optional field `tagger`
      if (jsonObj.get("tagger") != null && !jsonObj.get("tagger").isJsonNull()) {
        CommitUser.validateJsonElement(jsonObj.get("tagger"));
      }
      if ((jsonObj.get("url") != null && !jsonObj.get("url").isJsonNull()) && !jsonObj.get("url").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `url` to be a primitive type in the JSON string but got `%s`", jsonObj.get("url").toString()));
      }
      // validate the optional field `verification`
      if (jsonObj.get("verification") != null && !jsonObj.get("verification").isJsonNull()) {
        PayloadCommitVerification.validateJsonElement(jsonObj.get("verification"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!AnnotatedTag.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'AnnotatedTag' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<AnnotatedTag> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(AnnotatedTag.class));

       return (TypeAdapter<T>) new TypeAdapter<AnnotatedTag>() {
           @Override
           public void write(JsonWriter out, AnnotatedTag value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public AnnotatedTag read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of AnnotatedTag given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of AnnotatedTag
   * @throws IOException if the JSON string is invalid with respect to AnnotatedTag
   */
  public static AnnotatedTag fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, AnnotatedTag.class);
  }

  /**
   * Convert an instance of AnnotatedTag to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

