/*
 * Forgejo API
 * This documentation describes the Forgejo API.
 *
 * The version of the OpenAPI document: 14.0.3+gitea-1.22.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.smithyai.forgejoclient.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import dev.smithyai.forgejoclient.JSON;

/**
 * CreatePushMirrorOption
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-03-09T21:54:47.594851+01:00[Europe/Amsterdam]", comments = "Generator version: 7.20.0")
public class CreatePushMirrorOption {
  public static final String SERIALIZED_NAME_BRANCH_FILTER = "branch_filter";
  @SerializedName(SERIALIZED_NAME_BRANCH_FILTER)
  @javax.annotation.Nullable
  private String branchFilter;

  public static final String SERIALIZED_NAME_INTERVAL = "interval";
  @SerializedName(SERIALIZED_NAME_INTERVAL)
  @javax.annotation.Nullable
  private String interval;

  public static final String SERIALIZED_NAME_REMOTE_ADDRESS = "remote_address";
  @SerializedName(SERIALIZED_NAME_REMOTE_ADDRESS)
  @javax.annotation.Nullable
  private String remoteAddress;

  public static final String SERIALIZED_NAME_REMOTE_PASSWORD = "remote_password";
  @SerializedName(SERIALIZED_NAME_REMOTE_PASSWORD)
  @javax.annotation.Nullable
  private String remotePassword;

  public static final String SERIALIZED_NAME_REMOTE_USERNAME = "remote_username";
  @SerializedName(SERIALIZED_NAME_REMOTE_USERNAME)
  @javax.annotation.Nullable
  private String remoteUsername;

  public static final String SERIALIZED_NAME_SYNC_ON_COMMIT = "sync_on_commit";
  @SerializedName(SERIALIZED_NAME_SYNC_ON_COMMIT)
  @javax.annotation.Nullable
  private Boolean syncOnCommit;

  public static final String SERIALIZED_NAME_USE_SSH = "use_ssh";
  @SerializedName(SERIALIZED_NAME_USE_SSH)
  @javax.annotation.Nullable
  private Boolean useSsh;

  public CreatePushMirrorOption() {
  }

  public CreatePushMirrorOption branchFilter(@javax.annotation.Nullable String branchFilter) {
    this.branchFilter = branchFilter;
    return this;
  }

  /**
   * Get branchFilter
   * @return branchFilter
   */
  @javax.annotation.Nullable
  public String getBranchFilter() {
    return branchFilter;
  }

  public void setBranchFilter(@javax.annotation.Nullable String branchFilter) {
    this.branchFilter = branchFilter;
  }


  public CreatePushMirrorOption interval(@javax.annotation.Nullable String interval) {
    this.interval = interval;
    return this;
  }

  /**
   * Get interval
   * @return interval
   */
  @javax.annotation.Nullable
  public String getInterval() {
    return interval;
  }

  public void setInterval(@javax.annotation.Nullable String interval) {
    this.interval = interval;
  }


  public CreatePushMirrorOption remoteAddress(@javax.annotation.Nullable String remoteAddress) {
    this.remoteAddress = remoteAddress;
    return this;
  }

  /**
   * Get remoteAddress
   * @return remoteAddress
   */
  @javax.annotation.Nullable
  public String getRemoteAddress() {
    return remoteAddress;
  }

  public void setRemoteAddress(@javax.annotation.Nullable String remoteAddress) {
    this.remoteAddress = remoteAddress;
  }


  public CreatePushMirrorOption remotePassword(@javax.annotation.Nullable String remotePassword) {
    this.remotePassword = remotePassword;
    return this;
  }

  /**
   * Get remotePassword
   * @return remotePassword
   */
  @javax.annotation.Nullable
  public String getRemotePassword() {
    return remotePassword;
  }

  public void setRemotePassword(@javax.annotation.Nullable String remotePassword) {
    this.remotePassword = remotePassword;
  }


  public CreatePushMirrorOption remoteUsername(@javax.annotation.Nullable String remoteUsername) {
    this.remoteUsername = remoteUsername;
    return this;
  }

  /**
   * Get remoteUsername
   * @return remoteUsername
   */
  @javax.annotation.Nullable
  public String getRemoteUsername() {
    return remoteUsername;
  }

  public void setRemoteUsername(@javax.annotation.Nullable String remoteUsername) {
    this.remoteUsername = remoteUsername;
  }


  public CreatePushMirrorOption syncOnCommit(@javax.annotation.Nullable Boolean syncOnCommit) {
    this.syncOnCommit = syncOnCommit;
    return this;
  }

  /**
   * Get syncOnCommit
   * @return syncOnCommit
   */
  @javax.annotation.Nullable
  public Boolean getSyncOnCommit() {
    return syncOnCommit;
  }

  public void setSyncOnCommit(@javax.annotation.Nullable Boolean syncOnCommit) {
    this.syncOnCommit = syncOnCommit;
  }


  public CreatePushMirrorOption useSsh(@javax.annotation.Nullable Boolean useSsh) {
    this.useSsh = useSsh;
    return this;
  }

  /**
   * Get useSsh
   * @return useSsh
   */
  @javax.annotation.Nullable
  public Boolean getUseSsh() {
    return useSsh;
  }

  public void setUseSsh(@javax.annotation.Nullable Boolean useSsh) {
    this.useSsh = useSsh;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the CreatePushMirrorOption instance itself
   */
  public CreatePushMirrorOption putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreatePushMirrorOption createPushMirrorOption = (CreatePushMirrorOption) o;
    return Objects.equals(this.branchFilter, createPushMirrorOption.branchFilter) &&
        Objects.equals(this.interval, createPushMirrorOption.interval) &&
        Objects.equals(this.remoteAddress, createPushMirrorOption.remoteAddress) &&
        Objects.equals(this.remotePassword, createPushMirrorOption.remotePassword) &&
        Objects.equals(this.remoteUsername, createPushMirrorOption.remoteUsername) &&
        Objects.equals(this.syncOnCommit, createPushMirrorOption.syncOnCommit) &&
        Objects.equals(this.useSsh, createPushMirrorOption.useSsh)&&
        Objects.equals(this.additionalProperties, createPushMirrorOption.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(branchFilter, interval, remoteAddress, remotePassword, remoteUsername, syncOnCommit, useSsh, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreatePushMirrorOption {\n");
    sb.append("    branchFilter: ").append(toIndentedString(branchFilter)).append("\n");
    sb.append("    interval: ").append(toIndentedString(interval)).append("\n");
    sb.append("    remoteAddress: ").append(toIndentedString(remoteAddress)).append("\n");
    sb.append("    remotePassword: ").append(toIndentedString(remotePassword)).append("\n");
    sb.append("    remoteUsername: ").append(toIndentedString(remoteUsername)).append("\n");
    sb.append("    syncOnCommit: ").append(toIndentedString(syncOnCommit)).append("\n");
    sb.append("    useSsh: ").append(toIndentedString(useSsh)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("branch_filter", "interval", "remote_address", "remote_password", "remote_username", "sync_on_commit", "use_ssh"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to CreatePushMirrorOption
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!CreatePushMirrorOption.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in CreatePushMirrorOption is not found in the empty JSON string", CreatePushMirrorOption.openapiRequiredFields.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("branch_filter") != null && !jsonObj.get("branch_filter").isJsonNull()) && !jsonObj.get("branch_filter").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `branch_filter` to be a primitive type in the JSON string but got `%s`", jsonObj.get("branch_filter").toString()));
      }
      if ((jsonObj.get("interval") != null && !jsonObj.get("interval").isJsonNull()) && !jsonObj.get("interval").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `interval` to be a primitive type in the JSON string but got `%s`", jsonObj.get("interval").toString()));
      }
      if ((jsonObj.get("remote_address") != null && !jsonObj.get("remote_address").isJsonNull()) && !jsonObj.get("remote_address").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `remote_address` to be a primitive type in the JSON string but got `%s`", jsonObj.get("remote_address").toString()));
      }
      if ((jsonObj.get("remote_password") != null && !jsonObj.get("remote_password").isJsonNull()) && !jsonObj.get("remote_password").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `remote_password` to be a primitive type in the JSON string but got `%s`", jsonObj.get("remote_password").toString()));
      }
      if ((jsonObj.get("remote_username") != null && !jsonObj.get("remote_username").isJsonNull()) && !jsonObj.get("remote_username").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `remote_username` to be a primitive type in the JSON string but got `%s`", jsonObj.get("remote_username").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!CreatePushMirrorOption.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'CreatePushMirrorOption' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<CreatePushMirrorOption> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(CreatePushMirrorOption.class));

       return (TypeAdapter<T>) new TypeAdapter<CreatePushMirrorOption>() {
           @Override
           public void write(JsonWriter out, CreatePushMirrorOption value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additional properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   JsonElement jsonElement = gson.toJsonTree(entry.getValue());
                   if (jsonElement.isJsonArray()) {
                     obj.add(entry.getKey(), jsonElement.getAsJsonArray());
                   } else {
                     obj.add(entry.getKey(), jsonElement.getAsJsonObject());
                   }
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public CreatePushMirrorOption read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             JsonObject jsonObj = jsonElement.getAsJsonObject();
             // store additional fields in the deserialized instance
             CreatePushMirrorOption instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of CreatePushMirrorOption given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of CreatePushMirrorOption
   * @throws IOException if the JSON string is invalid with respect to CreatePushMirrorOption
   */
  public static CreatePushMirrorOption fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, CreatePushMirrorOption.class);
  }

  /**
   * Convert an instance of CreatePushMirrorOption to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

