/*
 * Forgejo API
 * This documentation describes the Forgejo API.
 *
 * The version of the OpenAPI document: 14.0.2-24-ea4f733de8+gitea-1.22.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.smithyai.forgejoclient.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import dev.smithyai.forgejoclient.JSON;

/**
 * CreateGPGKeyOption options create user GPG key
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-03-07T21:26:32.673342+01:00[Europe/Amsterdam]", comments = "Generator version: 7.20.0")
public class CreateGPGKeyOption {
  public static final String SERIALIZED_NAME_ARMORED_PUBLIC_KEY = "armored_public_key";
  @SerializedName(SERIALIZED_NAME_ARMORED_PUBLIC_KEY)
  @javax.annotation.Nonnull
  private String armoredPublicKey;

  public static final String SERIALIZED_NAME_ARMORED_SIGNATURE = "armored_signature";
  @SerializedName(SERIALIZED_NAME_ARMORED_SIGNATURE)
  @javax.annotation.Nullable
  private String armoredSignature;

  public CreateGPGKeyOption() {
  }

  public CreateGPGKeyOption armoredPublicKey(@javax.annotation.Nonnull String armoredPublicKey) {
    this.armoredPublicKey = armoredPublicKey;
    return this;
  }

  /**
   * An armored GPG key to add
   * @return armoredPublicKey
   */
  @javax.annotation.Nonnull
  public String getArmoredPublicKey() {
    return armoredPublicKey;
  }

  public void setArmoredPublicKey(@javax.annotation.Nonnull String armoredPublicKey) {
    this.armoredPublicKey = armoredPublicKey;
  }


  public CreateGPGKeyOption armoredSignature(@javax.annotation.Nullable String armoredSignature) {
    this.armoredSignature = armoredSignature;
    return this;
  }

  /**
   * Get armoredSignature
   * @return armoredSignature
   */
  @javax.annotation.Nullable
  public String getArmoredSignature() {
    return armoredSignature;
  }

  public void setArmoredSignature(@javax.annotation.Nullable String armoredSignature) {
    this.armoredSignature = armoredSignature;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateGPGKeyOption createGPGKeyOption = (CreateGPGKeyOption) o;
    return Objects.equals(this.armoredPublicKey, createGPGKeyOption.armoredPublicKey) &&
        Objects.equals(this.armoredSignature, createGPGKeyOption.armoredSignature);
  }

  @Override
  public int hashCode() {
    return Objects.hash(armoredPublicKey, armoredSignature);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateGPGKeyOption {\n");
    sb.append("    armoredPublicKey: ").append(toIndentedString(armoredPublicKey)).append("\n");
    sb.append("    armoredSignature: ").append(toIndentedString(armoredSignature)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("armored_public_key", "armored_signature"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("armored_public_key"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to CreateGPGKeyOption
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!CreateGPGKeyOption.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in CreateGPGKeyOption is not found in the empty JSON string", CreateGPGKeyOption.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!CreateGPGKeyOption.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `CreateGPGKeyOption` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : CreateGPGKeyOption.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("armored_public_key").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `armored_public_key` to be a primitive type in the JSON string but got `%s`", jsonObj.get("armored_public_key").toString()));
      }
      if ((jsonObj.get("armored_signature") != null && !jsonObj.get("armored_signature").isJsonNull()) && !jsonObj.get("armored_signature").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `armored_signature` to be a primitive type in the JSON string but got `%s`", jsonObj.get("armored_signature").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!CreateGPGKeyOption.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'CreateGPGKeyOption' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<CreateGPGKeyOption> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(CreateGPGKeyOption.class));

       return (TypeAdapter<T>) new TypeAdapter<CreateGPGKeyOption>() {
           @Override
           public void write(JsonWriter out, CreateGPGKeyOption value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public CreateGPGKeyOption read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of CreateGPGKeyOption given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of CreateGPGKeyOption
   * @throws IOException if the JSON string is invalid with respect to CreateGPGKeyOption
   */
  public static CreateGPGKeyOption fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, CreateGPGKeyOption.class);
  }

  /**
   * Convert an instance of CreateGPGKeyOption to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

