/*
 * Forgejo API
 * This documentation describes the Forgejo API.
 *
 * The version of the OpenAPI document: 14.0.3+gitea-1.22.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.smithyai.forgejoclient.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import dev.smithyai.forgejoclient.model.ExternalTracker;
import dev.smithyai.forgejoclient.model.ExternalWiki;
import dev.smithyai.forgejoclient.model.InternalTracker;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import dev.smithyai.forgejoclient.JSON;

/**
 * EditRepoOption options when editing a repository&#39;s properties
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-03-09T21:54:47.594851+01:00[Europe/Amsterdam]", comments = "Generator version: 7.20.0")
public class EditRepoOption {
  public static final String SERIALIZED_NAME_ALLOW_FAST_FORWARD_ONLY_MERGE = "allow_fast_forward_only_merge";
  @SerializedName(SERIALIZED_NAME_ALLOW_FAST_FORWARD_ONLY_MERGE)
  @javax.annotation.Nullable
  private Boolean allowFastForwardOnlyMerge;

  public static final String SERIALIZED_NAME_ALLOW_MANUAL_MERGE = "allow_manual_merge";
  @SerializedName(SERIALIZED_NAME_ALLOW_MANUAL_MERGE)
  @javax.annotation.Nullable
  private Boolean allowManualMerge;

  public static final String SERIALIZED_NAME_ALLOW_MERGE_COMMITS = "allow_merge_commits";
  @SerializedName(SERIALIZED_NAME_ALLOW_MERGE_COMMITS)
  @javax.annotation.Nullable
  private Boolean allowMergeCommits;

  public static final String SERIALIZED_NAME_ALLOW_REBASE = "allow_rebase";
  @SerializedName(SERIALIZED_NAME_ALLOW_REBASE)
  @javax.annotation.Nullable
  private Boolean allowRebase;

  public static final String SERIALIZED_NAME_ALLOW_REBASE_EXPLICIT = "allow_rebase_explicit";
  @SerializedName(SERIALIZED_NAME_ALLOW_REBASE_EXPLICIT)
  @javax.annotation.Nullable
  private Boolean allowRebaseExplicit;

  public static final String SERIALIZED_NAME_ALLOW_REBASE_UPDATE = "allow_rebase_update";
  @SerializedName(SERIALIZED_NAME_ALLOW_REBASE_UPDATE)
  @javax.annotation.Nullable
  private Boolean allowRebaseUpdate;

  public static final String SERIALIZED_NAME_ALLOW_SQUASH_MERGE = "allow_squash_merge";
  @SerializedName(SERIALIZED_NAME_ALLOW_SQUASH_MERGE)
  @javax.annotation.Nullable
  private Boolean allowSquashMerge;

  public static final String SERIALIZED_NAME_ARCHIVED = "archived";
  @SerializedName(SERIALIZED_NAME_ARCHIVED)
  @javax.annotation.Nullable
  private Boolean archived;

  public static final String SERIALIZED_NAME_AUTODETECT_MANUAL_MERGE = "autodetect_manual_merge";
  @SerializedName(SERIALIZED_NAME_AUTODETECT_MANUAL_MERGE)
  @javax.annotation.Nullable
  private Boolean autodetectManualMerge;

  public static final String SERIALIZED_NAME_DEFAULT_ALLOW_MAINTAINER_EDIT = "default_allow_maintainer_edit";
  @SerializedName(SERIALIZED_NAME_DEFAULT_ALLOW_MAINTAINER_EDIT)
  @javax.annotation.Nullable
  private Boolean defaultAllowMaintainerEdit;

  public static final String SERIALIZED_NAME_DEFAULT_BRANCH = "default_branch";
  @SerializedName(SERIALIZED_NAME_DEFAULT_BRANCH)
  @javax.annotation.Nullable
  private String defaultBranch;

  public static final String SERIALIZED_NAME_DEFAULT_DELETE_BRANCH_AFTER_MERGE = "default_delete_branch_after_merge";
  @SerializedName(SERIALIZED_NAME_DEFAULT_DELETE_BRANCH_AFTER_MERGE)
  @javax.annotation.Nullable
  private Boolean defaultDeleteBranchAfterMerge;

  public static final String SERIALIZED_NAME_DEFAULT_MERGE_STYLE = "default_merge_style";
  @SerializedName(SERIALIZED_NAME_DEFAULT_MERGE_STYLE)
  @javax.annotation.Nullable
  private String defaultMergeStyle;

  public static final String SERIALIZED_NAME_DEFAULT_UPDATE_STYLE = "default_update_style";
  @SerializedName(SERIALIZED_NAME_DEFAULT_UPDATE_STYLE)
  @javax.annotation.Nullable
  private String defaultUpdateStyle;

  public static final String SERIALIZED_NAME_DESCRIPTION = "description";
  @SerializedName(SERIALIZED_NAME_DESCRIPTION)
  @javax.annotation.Nullable
  private String description;

  public static final String SERIALIZED_NAME_ENABLE_PRUNE = "enable_prune";
  @SerializedName(SERIALIZED_NAME_ENABLE_PRUNE)
  @javax.annotation.Nullable
  private Boolean enablePrune;

  public static final String SERIALIZED_NAME_EXTERNAL_TRACKER = "external_tracker";
  @SerializedName(SERIALIZED_NAME_EXTERNAL_TRACKER)
  @javax.annotation.Nullable
  private ExternalTracker externalTracker;

  public static final String SERIALIZED_NAME_EXTERNAL_WIKI = "external_wiki";
  @SerializedName(SERIALIZED_NAME_EXTERNAL_WIKI)
  @javax.annotation.Nullable
  private ExternalWiki externalWiki;

  public static final String SERIALIZED_NAME_GLOBALLY_EDITABLE_WIKI = "globally_editable_wiki";
  @SerializedName(SERIALIZED_NAME_GLOBALLY_EDITABLE_WIKI)
  @javax.annotation.Nullable
  private Boolean globallyEditableWiki;

  public static final String SERIALIZED_NAME_HAS_ACTIONS = "has_actions";
  @SerializedName(SERIALIZED_NAME_HAS_ACTIONS)
  @javax.annotation.Nullable
  private Boolean hasActions;

  public static final String SERIALIZED_NAME_HAS_ISSUES = "has_issues";
  @SerializedName(SERIALIZED_NAME_HAS_ISSUES)
  @javax.annotation.Nullable
  private Boolean hasIssues;

  public static final String SERIALIZED_NAME_HAS_PACKAGES = "has_packages";
  @SerializedName(SERIALIZED_NAME_HAS_PACKAGES)
  @javax.annotation.Nullable
  private Boolean hasPackages;

  public static final String SERIALIZED_NAME_HAS_PROJECTS = "has_projects";
  @SerializedName(SERIALIZED_NAME_HAS_PROJECTS)
  @javax.annotation.Nullable
  private Boolean hasProjects;

  public static final String SERIALIZED_NAME_HAS_PULL_REQUESTS = "has_pull_requests";
  @SerializedName(SERIALIZED_NAME_HAS_PULL_REQUESTS)
  @javax.annotation.Nullable
  private Boolean hasPullRequests;

  public static final String SERIALIZED_NAME_HAS_RELEASES = "has_releases";
  @SerializedName(SERIALIZED_NAME_HAS_RELEASES)
  @javax.annotation.Nullable
  private Boolean hasReleases;

  public static final String SERIALIZED_NAME_HAS_WIKI = "has_wiki";
  @SerializedName(SERIALIZED_NAME_HAS_WIKI)
  @javax.annotation.Nullable
  private Boolean hasWiki;

  public static final String SERIALIZED_NAME_IGNORE_WHITESPACE_CONFLICTS = "ignore_whitespace_conflicts";
  @SerializedName(SERIALIZED_NAME_IGNORE_WHITESPACE_CONFLICTS)
  @javax.annotation.Nullable
  private Boolean ignoreWhitespaceConflicts;

  public static final String SERIALIZED_NAME_INTERNAL_TRACKER = "internal_tracker";
  @SerializedName(SERIALIZED_NAME_INTERNAL_TRACKER)
  @javax.annotation.Nullable
  private InternalTracker internalTracker;

  public static final String SERIALIZED_NAME_MIRROR_INTERVAL = "mirror_interval";
  @SerializedName(SERIALIZED_NAME_MIRROR_INTERVAL)
  @javax.annotation.Nullable
  private String mirrorInterval;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  @javax.annotation.Nullable
  private String name;

  public static final String SERIALIZED_NAME_PRIVATE = "private";
  @SerializedName(SERIALIZED_NAME_PRIVATE)
  @javax.annotation.Nullable
  private Boolean _private;

  public static final String SERIALIZED_NAME_TEMPLATE = "template";
  @SerializedName(SERIALIZED_NAME_TEMPLATE)
  @javax.annotation.Nullable
  private Boolean template;

  public static final String SERIALIZED_NAME_WEBSITE = "website";
  @SerializedName(SERIALIZED_NAME_WEBSITE)
  @javax.annotation.Nullable
  private String website;

  public static final String SERIALIZED_NAME_WIKI_BRANCH = "wiki_branch";
  @SerializedName(SERIALIZED_NAME_WIKI_BRANCH)
  @javax.annotation.Nullable
  private String wikiBranch;

  public EditRepoOption() {
  }

  public EditRepoOption allowFastForwardOnlyMerge(@javax.annotation.Nullable Boolean allowFastForwardOnlyMerge) {
    this.allowFastForwardOnlyMerge = allowFastForwardOnlyMerge;
    return this;
  }

  /**
   * either &#x60;true&#x60; to allow fast-forward-only merging pull requests, or &#x60;false&#x60; to prevent fast-forward-only merging.
   * @return allowFastForwardOnlyMerge
   */
  @javax.annotation.Nullable
  public Boolean getAllowFastForwardOnlyMerge() {
    return allowFastForwardOnlyMerge;
  }

  public void setAllowFastForwardOnlyMerge(@javax.annotation.Nullable Boolean allowFastForwardOnlyMerge) {
    this.allowFastForwardOnlyMerge = allowFastForwardOnlyMerge;
  }


  public EditRepoOption allowManualMerge(@javax.annotation.Nullable Boolean allowManualMerge) {
    this.allowManualMerge = allowManualMerge;
    return this;
  }

  /**
   * either &#x60;true&#x60; to allow mark pr as merged manually, or &#x60;false&#x60; to prevent it.
   * @return allowManualMerge
   */
  @javax.annotation.Nullable
  public Boolean getAllowManualMerge() {
    return allowManualMerge;
  }

  public void setAllowManualMerge(@javax.annotation.Nullable Boolean allowManualMerge) {
    this.allowManualMerge = allowManualMerge;
  }


  public EditRepoOption allowMergeCommits(@javax.annotation.Nullable Boolean allowMergeCommits) {
    this.allowMergeCommits = allowMergeCommits;
    return this;
  }

  /**
   * either &#x60;true&#x60; to allow merging pull requests with a merge commit, or &#x60;false&#x60; to prevent merging pull requests with merge commits.
   * @return allowMergeCommits
   */
  @javax.annotation.Nullable
  public Boolean getAllowMergeCommits() {
    return allowMergeCommits;
  }

  public void setAllowMergeCommits(@javax.annotation.Nullable Boolean allowMergeCommits) {
    this.allowMergeCommits = allowMergeCommits;
  }


  public EditRepoOption allowRebase(@javax.annotation.Nullable Boolean allowRebase) {
    this.allowRebase = allowRebase;
    return this;
  }

  /**
   * either &#x60;true&#x60; to allow rebase-merging pull requests, or &#x60;false&#x60; to prevent rebase-merging.
   * @return allowRebase
   */
  @javax.annotation.Nullable
  public Boolean getAllowRebase() {
    return allowRebase;
  }

  public void setAllowRebase(@javax.annotation.Nullable Boolean allowRebase) {
    this.allowRebase = allowRebase;
  }


  public EditRepoOption allowRebaseExplicit(@javax.annotation.Nullable Boolean allowRebaseExplicit) {
    this.allowRebaseExplicit = allowRebaseExplicit;
    return this;
  }

  /**
   * either &#x60;true&#x60; to allow rebase with explicit merge commits (--no-ff), or &#x60;false&#x60; to prevent rebase with explicit merge commits.
   * @return allowRebaseExplicit
   */
  @javax.annotation.Nullable
  public Boolean getAllowRebaseExplicit() {
    return allowRebaseExplicit;
  }

  public void setAllowRebaseExplicit(@javax.annotation.Nullable Boolean allowRebaseExplicit) {
    this.allowRebaseExplicit = allowRebaseExplicit;
  }


  public EditRepoOption allowRebaseUpdate(@javax.annotation.Nullable Boolean allowRebaseUpdate) {
    this.allowRebaseUpdate = allowRebaseUpdate;
    return this;
  }

  /**
   * either &#x60;true&#x60; to allow updating pull request branch by rebase, or &#x60;false&#x60; to prevent it.
   * @return allowRebaseUpdate
   */
  @javax.annotation.Nullable
  public Boolean getAllowRebaseUpdate() {
    return allowRebaseUpdate;
  }

  public void setAllowRebaseUpdate(@javax.annotation.Nullable Boolean allowRebaseUpdate) {
    this.allowRebaseUpdate = allowRebaseUpdate;
  }


  public EditRepoOption allowSquashMerge(@javax.annotation.Nullable Boolean allowSquashMerge) {
    this.allowSquashMerge = allowSquashMerge;
    return this;
  }

  /**
   * either &#x60;true&#x60; to allow squash-merging pull requests, or &#x60;false&#x60; to prevent squash-merging.
   * @return allowSquashMerge
   */
  @javax.annotation.Nullable
  public Boolean getAllowSquashMerge() {
    return allowSquashMerge;
  }

  public void setAllowSquashMerge(@javax.annotation.Nullable Boolean allowSquashMerge) {
    this.allowSquashMerge = allowSquashMerge;
  }


  public EditRepoOption archived(@javax.annotation.Nullable Boolean archived) {
    this.archived = archived;
    return this;
  }

  /**
   * set to &#x60;true&#x60; to archive this repository.
   * @return archived
   */
  @javax.annotation.Nullable
  public Boolean getArchived() {
    return archived;
  }

  public void setArchived(@javax.annotation.Nullable Boolean archived) {
    this.archived = archived;
  }


  public EditRepoOption autodetectManualMerge(@javax.annotation.Nullable Boolean autodetectManualMerge) {
    this.autodetectManualMerge = autodetectManualMerge;
    return this;
  }

  /**
   * either &#x60;true&#x60; to enable AutodetectManualMerge, or &#x60;false&#x60; to prevent it. Note: In some special cases, misjudgments can occur.
   * @return autodetectManualMerge
   */
  @javax.annotation.Nullable
  public Boolean getAutodetectManualMerge() {
    return autodetectManualMerge;
  }

  public void setAutodetectManualMerge(@javax.annotation.Nullable Boolean autodetectManualMerge) {
    this.autodetectManualMerge = autodetectManualMerge;
  }


  public EditRepoOption defaultAllowMaintainerEdit(@javax.annotation.Nullable Boolean defaultAllowMaintainerEdit) {
    this.defaultAllowMaintainerEdit = defaultAllowMaintainerEdit;
    return this;
  }

  /**
   * set to &#x60;true&#x60; to allow edits from maintainers by default
   * @return defaultAllowMaintainerEdit
   */
  @javax.annotation.Nullable
  public Boolean getDefaultAllowMaintainerEdit() {
    return defaultAllowMaintainerEdit;
  }

  public void setDefaultAllowMaintainerEdit(@javax.annotation.Nullable Boolean defaultAllowMaintainerEdit) {
    this.defaultAllowMaintainerEdit = defaultAllowMaintainerEdit;
  }


  public EditRepoOption defaultBranch(@javax.annotation.Nullable String defaultBranch) {
    this.defaultBranch = defaultBranch;
    return this;
  }

  /**
   * sets the default branch for this repository.
   * @return defaultBranch
   */
  @javax.annotation.Nullable
  public String getDefaultBranch() {
    return defaultBranch;
  }

  public void setDefaultBranch(@javax.annotation.Nullable String defaultBranch) {
    this.defaultBranch = defaultBranch;
  }


  public EditRepoOption defaultDeleteBranchAfterMerge(@javax.annotation.Nullable Boolean defaultDeleteBranchAfterMerge) {
    this.defaultDeleteBranchAfterMerge = defaultDeleteBranchAfterMerge;
    return this;
  }

  /**
   * set to &#x60;true&#x60; to delete pr branch after merge by default
   * @return defaultDeleteBranchAfterMerge
   */
  @javax.annotation.Nullable
  public Boolean getDefaultDeleteBranchAfterMerge() {
    return defaultDeleteBranchAfterMerge;
  }

  public void setDefaultDeleteBranchAfterMerge(@javax.annotation.Nullable Boolean defaultDeleteBranchAfterMerge) {
    this.defaultDeleteBranchAfterMerge = defaultDeleteBranchAfterMerge;
  }


  public EditRepoOption defaultMergeStyle(@javax.annotation.Nullable String defaultMergeStyle) {
    this.defaultMergeStyle = defaultMergeStyle;
    return this;
  }

  /**
   * set to a merge style to be used by this repository: \&quot;merge\&quot;, \&quot;rebase\&quot;, \&quot;rebase-merge\&quot;, \&quot;squash\&quot;, \&quot;fast-forward-only\&quot;, \&quot;manually-merged\&quot;, or \&quot;rebase-update-only\&quot;.
   * @return defaultMergeStyle
   */
  @javax.annotation.Nullable
  public String getDefaultMergeStyle() {
    return defaultMergeStyle;
  }

  public void setDefaultMergeStyle(@javax.annotation.Nullable String defaultMergeStyle) {
    this.defaultMergeStyle = defaultMergeStyle;
  }


  public EditRepoOption defaultUpdateStyle(@javax.annotation.Nullable String defaultUpdateStyle) {
    this.defaultUpdateStyle = defaultUpdateStyle;
    return this;
  }

  /**
   * set to a update style to be used by this repository: \&quot;rebase\&quot; or \&quot;merge\&quot;
   * @return defaultUpdateStyle
   */
  @javax.annotation.Nullable
  public String getDefaultUpdateStyle() {
    return defaultUpdateStyle;
  }

  public void setDefaultUpdateStyle(@javax.annotation.Nullable String defaultUpdateStyle) {
    this.defaultUpdateStyle = defaultUpdateStyle;
  }


  public EditRepoOption description(@javax.annotation.Nullable String description) {
    this.description = description;
    return this;
  }

  /**
   * a short description of the repository.
   * @return description
   */
  @javax.annotation.Nullable
  public String getDescription() {
    return description;
  }

  public void setDescription(@javax.annotation.Nullable String description) {
    this.description = description;
  }


  public EditRepoOption enablePrune(@javax.annotation.Nullable Boolean enablePrune) {
    this.enablePrune = enablePrune;
    return this;
  }

  /**
   * enable prune - remove obsolete remote-tracking references when mirroring
   * @return enablePrune
   */
  @javax.annotation.Nullable
  public Boolean getEnablePrune() {
    return enablePrune;
  }

  public void setEnablePrune(@javax.annotation.Nullable Boolean enablePrune) {
    this.enablePrune = enablePrune;
  }


  public EditRepoOption externalTracker(@javax.annotation.Nullable ExternalTracker externalTracker) {
    this.externalTracker = externalTracker;
    return this;
  }

  /**
   * Get externalTracker
   * @return externalTracker
   */
  @javax.annotation.Nullable
  public ExternalTracker getExternalTracker() {
    return externalTracker;
  }

  public void setExternalTracker(@javax.annotation.Nullable ExternalTracker externalTracker) {
    this.externalTracker = externalTracker;
  }


  public EditRepoOption externalWiki(@javax.annotation.Nullable ExternalWiki externalWiki) {
    this.externalWiki = externalWiki;
    return this;
  }

  /**
   * Get externalWiki
   * @return externalWiki
   */
  @javax.annotation.Nullable
  public ExternalWiki getExternalWiki() {
    return externalWiki;
  }

  public void setExternalWiki(@javax.annotation.Nullable ExternalWiki externalWiki) {
    this.externalWiki = externalWiki;
  }


  public EditRepoOption globallyEditableWiki(@javax.annotation.Nullable Boolean globallyEditableWiki) {
    this.globallyEditableWiki = globallyEditableWiki;
    return this;
  }

  /**
   * set the globally editable state of the wiki
   * @return globallyEditableWiki
   */
  @javax.annotation.Nullable
  public Boolean getGloballyEditableWiki() {
    return globallyEditableWiki;
  }

  public void setGloballyEditableWiki(@javax.annotation.Nullable Boolean globallyEditableWiki) {
    this.globallyEditableWiki = globallyEditableWiki;
  }


  public EditRepoOption hasActions(@javax.annotation.Nullable Boolean hasActions) {
    this.hasActions = hasActions;
    return this;
  }

  /**
   * either &#x60;true&#x60; to enable actions unit, or &#x60;false&#x60; to disable them.
   * @return hasActions
   */
  @javax.annotation.Nullable
  public Boolean getHasActions() {
    return hasActions;
  }

  public void setHasActions(@javax.annotation.Nullable Boolean hasActions) {
    this.hasActions = hasActions;
  }


  public EditRepoOption hasIssues(@javax.annotation.Nullable Boolean hasIssues) {
    this.hasIssues = hasIssues;
    return this;
  }

  /**
   * either &#x60;true&#x60; to enable issues for this repository or &#x60;false&#x60; to disable them.
   * @return hasIssues
   */
  @javax.annotation.Nullable
  public Boolean getHasIssues() {
    return hasIssues;
  }

  public void setHasIssues(@javax.annotation.Nullable Boolean hasIssues) {
    this.hasIssues = hasIssues;
  }


  public EditRepoOption hasPackages(@javax.annotation.Nullable Boolean hasPackages) {
    this.hasPackages = hasPackages;
    return this;
  }

  /**
   * either &#x60;true&#x60; to enable packages unit, or &#x60;false&#x60; to disable them.
   * @return hasPackages
   */
  @javax.annotation.Nullable
  public Boolean getHasPackages() {
    return hasPackages;
  }

  public void setHasPackages(@javax.annotation.Nullable Boolean hasPackages) {
    this.hasPackages = hasPackages;
  }


  public EditRepoOption hasProjects(@javax.annotation.Nullable Boolean hasProjects) {
    this.hasProjects = hasProjects;
    return this;
  }

  /**
   * either &#x60;true&#x60; to enable project unit, or &#x60;false&#x60; to disable them.
   * @return hasProjects
   */
  @javax.annotation.Nullable
  public Boolean getHasProjects() {
    return hasProjects;
  }

  public void setHasProjects(@javax.annotation.Nullable Boolean hasProjects) {
    this.hasProjects = hasProjects;
  }


  public EditRepoOption hasPullRequests(@javax.annotation.Nullable Boolean hasPullRequests) {
    this.hasPullRequests = hasPullRequests;
    return this;
  }

  /**
   * either &#x60;true&#x60; to allow pull requests, or &#x60;false&#x60; to prevent pull request.
   * @return hasPullRequests
   */
  @javax.annotation.Nullable
  public Boolean getHasPullRequests() {
    return hasPullRequests;
  }

  public void setHasPullRequests(@javax.annotation.Nullable Boolean hasPullRequests) {
    this.hasPullRequests = hasPullRequests;
  }


  public EditRepoOption hasReleases(@javax.annotation.Nullable Boolean hasReleases) {
    this.hasReleases = hasReleases;
    return this;
  }

  /**
   * either &#x60;true&#x60; to enable releases unit, or &#x60;false&#x60; to disable them.
   * @return hasReleases
   */
  @javax.annotation.Nullable
  public Boolean getHasReleases() {
    return hasReleases;
  }

  public void setHasReleases(@javax.annotation.Nullable Boolean hasReleases) {
    this.hasReleases = hasReleases;
  }


  public EditRepoOption hasWiki(@javax.annotation.Nullable Boolean hasWiki) {
    this.hasWiki = hasWiki;
    return this;
  }

  /**
   * either &#x60;true&#x60; to enable the wiki for this repository or &#x60;false&#x60; to disable it.
   * @return hasWiki
   */
  @javax.annotation.Nullable
  public Boolean getHasWiki() {
    return hasWiki;
  }

  public void setHasWiki(@javax.annotation.Nullable Boolean hasWiki) {
    this.hasWiki = hasWiki;
  }


  public EditRepoOption ignoreWhitespaceConflicts(@javax.annotation.Nullable Boolean ignoreWhitespaceConflicts) {
    this.ignoreWhitespaceConflicts = ignoreWhitespaceConflicts;
    return this;
  }

  /**
   * either &#x60;true&#x60; to ignore whitespace for conflicts, or &#x60;false&#x60; to not ignore whitespace.
   * @return ignoreWhitespaceConflicts
   */
  @javax.annotation.Nullable
  public Boolean getIgnoreWhitespaceConflicts() {
    return ignoreWhitespaceConflicts;
  }

  public void setIgnoreWhitespaceConflicts(@javax.annotation.Nullable Boolean ignoreWhitespaceConflicts) {
    this.ignoreWhitespaceConflicts = ignoreWhitespaceConflicts;
  }


  public EditRepoOption internalTracker(@javax.annotation.Nullable InternalTracker internalTracker) {
    this.internalTracker = internalTracker;
    return this;
  }

  /**
   * Get internalTracker
   * @return internalTracker
   */
  @javax.annotation.Nullable
  public InternalTracker getInternalTracker() {
    return internalTracker;
  }

  public void setInternalTracker(@javax.annotation.Nullable InternalTracker internalTracker) {
    this.internalTracker = internalTracker;
  }


  public EditRepoOption mirrorInterval(@javax.annotation.Nullable String mirrorInterval) {
    this.mirrorInterval = mirrorInterval;
    return this;
  }

  /**
   * set to a string like &#x60;8h30m0s&#x60; to set the mirror interval time
   * @return mirrorInterval
   */
  @javax.annotation.Nullable
  public String getMirrorInterval() {
    return mirrorInterval;
  }

  public void setMirrorInterval(@javax.annotation.Nullable String mirrorInterval) {
    this.mirrorInterval = mirrorInterval;
  }


  public EditRepoOption name(@javax.annotation.Nullable String name) {
    this.name = name;
    return this;
  }

  /**
   * name of the repository
   * @return name
   */
  @javax.annotation.Nullable
  public String getName() {
    return name;
  }

  public void setName(@javax.annotation.Nullable String name) {
    this.name = name;
  }


  public EditRepoOption _private(@javax.annotation.Nullable Boolean _private) {
    this._private = _private;
    return this;
  }

  /**
   * either &#x60;true&#x60; to make the repository private or &#x60;false&#x60; to make it public. Note: you will get a 422 error if the organization restricts changing repository visibility to organization owners and a non-owner tries to change the value of private.
   * @return _private
   */
  @javax.annotation.Nullable
  public Boolean getPrivate() {
    return _private;
  }

  public void setPrivate(@javax.annotation.Nullable Boolean _private) {
    this._private = _private;
  }


  public EditRepoOption template(@javax.annotation.Nullable Boolean template) {
    this.template = template;
    return this;
  }

  /**
   * either &#x60;true&#x60; to make this repository a template or &#x60;false&#x60; to make it a normal repository
   * @return template
   */
  @javax.annotation.Nullable
  public Boolean getTemplate() {
    return template;
  }

  public void setTemplate(@javax.annotation.Nullable Boolean template) {
    this.template = template;
  }


  public EditRepoOption website(@javax.annotation.Nullable String website) {
    this.website = website;
    return this;
  }

  /**
   * a URL with more information about the repository.
   * @return website
   */
  @javax.annotation.Nullable
  public String getWebsite() {
    return website;
  }

  public void setWebsite(@javax.annotation.Nullable String website) {
    this.website = website;
  }


  public EditRepoOption wikiBranch(@javax.annotation.Nullable String wikiBranch) {
    this.wikiBranch = wikiBranch;
    return this;
  }

  /**
   * sets the branch used for this repository&#39;s wiki.
   * @return wikiBranch
   */
  @javax.annotation.Nullable
  public String getWikiBranch() {
    return wikiBranch;
  }

  public void setWikiBranch(@javax.annotation.Nullable String wikiBranch) {
    this.wikiBranch = wikiBranch;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the EditRepoOption instance itself
   */
  public EditRepoOption putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EditRepoOption editRepoOption = (EditRepoOption) o;
    return Objects.equals(this.allowFastForwardOnlyMerge, editRepoOption.allowFastForwardOnlyMerge) &&
        Objects.equals(this.allowManualMerge, editRepoOption.allowManualMerge) &&
        Objects.equals(this.allowMergeCommits, editRepoOption.allowMergeCommits) &&
        Objects.equals(this.allowRebase, editRepoOption.allowRebase) &&
        Objects.equals(this.allowRebaseExplicit, editRepoOption.allowRebaseExplicit) &&
        Objects.equals(this.allowRebaseUpdate, editRepoOption.allowRebaseUpdate) &&
        Objects.equals(this.allowSquashMerge, editRepoOption.allowSquashMerge) &&
        Objects.equals(this.archived, editRepoOption.archived) &&
        Objects.equals(this.autodetectManualMerge, editRepoOption.autodetectManualMerge) &&
        Objects.equals(this.defaultAllowMaintainerEdit, editRepoOption.defaultAllowMaintainerEdit) &&
        Objects.equals(this.defaultBranch, editRepoOption.defaultBranch) &&
        Objects.equals(this.defaultDeleteBranchAfterMerge, editRepoOption.defaultDeleteBranchAfterMerge) &&
        Objects.equals(this.defaultMergeStyle, editRepoOption.defaultMergeStyle) &&
        Objects.equals(this.defaultUpdateStyle, editRepoOption.defaultUpdateStyle) &&
        Objects.equals(this.description, editRepoOption.description) &&
        Objects.equals(this.enablePrune, editRepoOption.enablePrune) &&
        Objects.equals(this.externalTracker, editRepoOption.externalTracker) &&
        Objects.equals(this.externalWiki, editRepoOption.externalWiki) &&
        Objects.equals(this.globallyEditableWiki, editRepoOption.globallyEditableWiki) &&
        Objects.equals(this.hasActions, editRepoOption.hasActions) &&
        Objects.equals(this.hasIssues, editRepoOption.hasIssues) &&
        Objects.equals(this.hasPackages, editRepoOption.hasPackages) &&
        Objects.equals(this.hasProjects, editRepoOption.hasProjects) &&
        Objects.equals(this.hasPullRequests, editRepoOption.hasPullRequests) &&
        Objects.equals(this.hasReleases, editRepoOption.hasReleases) &&
        Objects.equals(this.hasWiki, editRepoOption.hasWiki) &&
        Objects.equals(this.ignoreWhitespaceConflicts, editRepoOption.ignoreWhitespaceConflicts) &&
        Objects.equals(this.internalTracker, editRepoOption.internalTracker) &&
        Objects.equals(this.mirrorInterval, editRepoOption.mirrorInterval) &&
        Objects.equals(this.name, editRepoOption.name) &&
        Objects.equals(this._private, editRepoOption._private) &&
        Objects.equals(this.template, editRepoOption.template) &&
        Objects.equals(this.website, editRepoOption.website) &&
        Objects.equals(this.wikiBranch, editRepoOption.wikiBranch)&&
        Objects.equals(this.additionalProperties, editRepoOption.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(allowFastForwardOnlyMerge, allowManualMerge, allowMergeCommits, allowRebase, allowRebaseExplicit, allowRebaseUpdate, allowSquashMerge, archived, autodetectManualMerge, defaultAllowMaintainerEdit, defaultBranch, defaultDeleteBranchAfterMerge, defaultMergeStyle, defaultUpdateStyle, description, enablePrune, externalTracker, externalWiki, globallyEditableWiki, hasActions, hasIssues, hasPackages, hasProjects, hasPullRequests, hasReleases, hasWiki, ignoreWhitespaceConflicts, internalTracker, mirrorInterval, name, _private, template, website, wikiBranch, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EditRepoOption {\n");
    sb.append("    allowFastForwardOnlyMerge: ").append(toIndentedString(allowFastForwardOnlyMerge)).append("\n");
    sb.append("    allowManualMerge: ").append(toIndentedString(allowManualMerge)).append("\n");
    sb.append("    allowMergeCommits: ").append(toIndentedString(allowMergeCommits)).append("\n");
    sb.append("    allowRebase: ").append(toIndentedString(allowRebase)).append("\n");
    sb.append("    allowRebaseExplicit: ").append(toIndentedString(allowRebaseExplicit)).append("\n");
    sb.append("    allowRebaseUpdate: ").append(toIndentedString(allowRebaseUpdate)).append("\n");
    sb.append("    allowSquashMerge: ").append(toIndentedString(allowSquashMerge)).append("\n");
    sb.append("    archived: ").append(toIndentedString(archived)).append("\n");
    sb.append("    autodetectManualMerge: ").append(toIndentedString(autodetectManualMerge)).append("\n");
    sb.append("    defaultAllowMaintainerEdit: ").append(toIndentedString(defaultAllowMaintainerEdit)).append("\n");
    sb.append("    defaultBranch: ").append(toIndentedString(defaultBranch)).append("\n");
    sb.append("    defaultDeleteBranchAfterMerge: ").append(toIndentedString(defaultDeleteBranchAfterMerge)).append("\n");
    sb.append("    defaultMergeStyle: ").append(toIndentedString(defaultMergeStyle)).append("\n");
    sb.append("    defaultUpdateStyle: ").append(toIndentedString(defaultUpdateStyle)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    enablePrune: ").append(toIndentedString(enablePrune)).append("\n");
    sb.append("    externalTracker: ").append(toIndentedString(externalTracker)).append("\n");
    sb.append("    externalWiki: ").append(toIndentedString(externalWiki)).append("\n");
    sb.append("    globallyEditableWiki: ").append(toIndentedString(globallyEditableWiki)).append("\n");
    sb.append("    hasActions: ").append(toIndentedString(hasActions)).append("\n");
    sb.append("    hasIssues: ").append(toIndentedString(hasIssues)).append("\n");
    sb.append("    hasPackages: ").append(toIndentedString(hasPackages)).append("\n");
    sb.append("    hasProjects: ").append(toIndentedString(hasProjects)).append("\n");
    sb.append("    hasPullRequests: ").append(toIndentedString(hasPullRequests)).append("\n");
    sb.append("    hasReleases: ").append(toIndentedString(hasReleases)).append("\n");
    sb.append("    hasWiki: ").append(toIndentedString(hasWiki)).append("\n");
    sb.append("    ignoreWhitespaceConflicts: ").append(toIndentedString(ignoreWhitespaceConflicts)).append("\n");
    sb.append("    internalTracker: ").append(toIndentedString(internalTracker)).append("\n");
    sb.append("    mirrorInterval: ").append(toIndentedString(mirrorInterval)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    _private: ").append(toIndentedString(_private)).append("\n");
    sb.append("    template: ").append(toIndentedString(template)).append("\n");
    sb.append("    website: ").append(toIndentedString(website)).append("\n");
    sb.append("    wikiBranch: ").append(toIndentedString(wikiBranch)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("allow_fast_forward_only_merge", "allow_manual_merge", "allow_merge_commits", "allow_rebase", "allow_rebase_explicit", "allow_rebase_update", "allow_squash_merge", "archived", "autodetect_manual_merge", "default_allow_maintainer_edit", "default_branch", "default_delete_branch_after_merge", "default_merge_style", "default_update_style", "description", "enable_prune", "external_tracker", "external_wiki", "globally_editable_wiki", "has_actions", "has_issues", "has_packages", "has_projects", "has_pull_requests", "has_releases", "has_wiki", "ignore_whitespace_conflicts", "internal_tracker", "mirror_interval", "name", "private", "template", "website", "wiki_branch"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to EditRepoOption
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!EditRepoOption.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in EditRepoOption is not found in the empty JSON string", EditRepoOption.openapiRequiredFields.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("default_branch") != null && !jsonObj.get("default_branch").isJsonNull()) && !jsonObj.get("default_branch").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `default_branch` to be a primitive type in the JSON string but got `%s`", jsonObj.get("default_branch").toString()));
      }
      if ((jsonObj.get("default_merge_style") != null && !jsonObj.get("default_merge_style").isJsonNull()) && !jsonObj.get("default_merge_style").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `default_merge_style` to be a primitive type in the JSON string but got `%s`", jsonObj.get("default_merge_style").toString()));
      }
      if ((jsonObj.get("default_update_style") != null && !jsonObj.get("default_update_style").isJsonNull()) && !jsonObj.get("default_update_style").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `default_update_style` to be a primitive type in the JSON string but got `%s`", jsonObj.get("default_update_style").toString()));
      }
      if ((jsonObj.get("description") != null && !jsonObj.get("description").isJsonNull()) && !jsonObj.get("description").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `description` to be a primitive type in the JSON string but got `%s`", jsonObj.get("description").toString()));
      }
      // validate the optional field `external_tracker`
      if (jsonObj.get("external_tracker") != null && !jsonObj.get("external_tracker").isJsonNull()) {
        ExternalTracker.validateJsonElement(jsonObj.get("external_tracker"));
      }
      // validate the optional field `external_wiki`
      if (jsonObj.get("external_wiki") != null && !jsonObj.get("external_wiki").isJsonNull()) {
        ExternalWiki.validateJsonElement(jsonObj.get("external_wiki"));
      }
      // validate the optional field `internal_tracker`
      if (jsonObj.get("internal_tracker") != null && !jsonObj.get("internal_tracker").isJsonNull()) {
        InternalTracker.validateJsonElement(jsonObj.get("internal_tracker"));
      }
      if ((jsonObj.get("mirror_interval") != null && !jsonObj.get("mirror_interval").isJsonNull()) && !jsonObj.get("mirror_interval").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `mirror_interval` to be a primitive type in the JSON string but got `%s`", jsonObj.get("mirror_interval").toString()));
      }
      if ((jsonObj.get("name") != null && !jsonObj.get("name").isJsonNull()) && !jsonObj.get("name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("name").toString()));
      }
      if ((jsonObj.get("website") != null && !jsonObj.get("website").isJsonNull()) && !jsonObj.get("website").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `website` to be a primitive type in the JSON string but got `%s`", jsonObj.get("website").toString()));
      }
      if ((jsonObj.get("wiki_branch") != null && !jsonObj.get("wiki_branch").isJsonNull()) && !jsonObj.get("wiki_branch").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `wiki_branch` to be a primitive type in the JSON string but got `%s`", jsonObj.get("wiki_branch").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!EditRepoOption.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'EditRepoOption' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<EditRepoOption> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(EditRepoOption.class));

       return (TypeAdapter<T>) new TypeAdapter<EditRepoOption>() {
           @Override
           public void write(JsonWriter out, EditRepoOption value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additional properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   JsonElement jsonElement = gson.toJsonTree(entry.getValue());
                   if (jsonElement.isJsonArray()) {
                     obj.add(entry.getKey(), jsonElement.getAsJsonArray());
                   } else {
                     obj.add(entry.getKey(), jsonElement.getAsJsonObject());
                   }
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public EditRepoOption read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             JsonObject jsonObj = jsonElement.getAsJsonObject();
             // store additional fields in the deserialized instance
             EditRepoOption instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of EditRepoOption given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of EditRepoOption
   * @throws IOException if the JSON string is invalid with respect to EditRepoOption
   */
  public static EditRepoOption fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, EditRepoOption.class);
  }

  /**
   * Convert an instance of EditRepoOption to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

