/*
 * Forgejo API
 * This documentation describes the Forgejo API.
 *
 * The version of the OpenAPI document: 14.0.2-24-ea4f733de8+gitea-1.22.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.smithyai.forgejoclient.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import dev.smithyai.forgejoclient.model.Comment;
import dev.smithyai.forgejoclient.model.Issue;
import dev.smithyai.forgejoclient.model.Label;
import dev.smithyai.forgejoclient.model.Milestone;
import dev.smithyai.forgejoclient.model.Team;
import dev.smithyai.forgejoclient.model.TrackedTime;
import dev.smithyai.forgejoclient.model.User;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import dev.smithyai.forgejoclient.JSON;

/**
 * TimelineComment represents a timeline comment (comment of any type) on a commit or issue
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-03-07T21:26:32.673342+01:00[Europe/Amsterdam]", comments = "Generator version: 7.20.0")
public class TimelineComment {
  public static final String SERIALIZED_NAME_ASSIGNEE = "assignee";
  @SerializedName(SERIALIZED_NAME_ASSIGNEE)
  @javax.annotation.Nullable
  private User assignee;

  public static final String SERIALIZED_NAME_ASSIGNEE_TEAM = "assignee_team";
  @SerializedName(SERIALIZED_NAME_ASSIGNEE_TEAM)
  @javax.annotation.Nullable
  private Team assigneeTeam;

  public static final String SERIALIZED_NAME_BODY = "body";
  @SerializedName(SERIALIZED_NAME_BODY)
  @javax.annotation.Nullable
  private String body;

  public static final String SERIALIZED_NAME_CREATED_AT = "created_at";
  @SerializedName(SERIALIZED_NAME_CREATED_AT)
  @javax.annotation.Nullable
  private OffsetDateTime createdAt;

  public static final String SERIALIZED_NAME_DEPENDENT_ISSUE = "dependent_issue";
  @SerializedName(SERIALIZED_NAME_DEPENDENT_ISSUE)
  @javax.annotation.Nullable
  private Issue dependentIssue;

  public static final String SERIALIZED_NAME_HTML_URL = "html_url";
  @SerializedName(SERIALIZED_NAME_HTML_URL)
  @javax.annotation.Nullable
  private String htmlUrl;

  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  @javax.annotation.Nullable
  private Long id;

  public static final String SERIALIZED_NAME_ISSUE_URL = "issue_url";
  @SerializedName(SERIALIZED_NAME_ISSUE_URL)
  @javax.annotation.Nullable
  private String issueUrl;

  public static final String SERIALIZED_NAME_LABEL = "label";
  @SerializedName(SERIALIZED_NAME_LABEL)
  @javax.annotation.Nullable
  private Label label;

  public static final String SERIALIZED_NAME_MILESTONE = "milestone";
  @SerializedName(SERIALIZED_NAME_MILESTONE)
  @javax.annotation.Nullable
  private Milestone milestone;

  public static final String SERIALIZED_NAME_NEW_REF = "new_ref";
  @SerializedName(SERIALIZED_NAME_NEW_REF)
  @javax.annotation.Nullable
  private String newRef;

  public static final String SERIALIZED_NAME_NEW_TITLE = "new_title";
  @SerializedName(SERIALIZED_NAME_NEW_TITLE)
  @javax.annotation.Nullable
  private String newTitle;

  public static final String SERIALIZED_NAME_OLD_MILESTONE = "old_milestone";
  @SerializedName(SERIALIZED_NAME_OLD_MILESTONE)
  @javax.annotation.Nullable
  private Milestone oldMilestone;

  public static final String SERIALIZED_NAME_OLD_PROJECT_ID = "old_project_id";
  @SerializedName(SERIALIZED_NAME_OLD_PROJECT_ID)
  @javax.annotation.Nullable
  private Long oldProjectId;

  public static final String SERIALIZED_NAME_OLD_REF = "old_ref";
  @SerializedName(SERIALIZED_NAME_OLD_REF)
  @javax.annotation.Nullable
  private String oldRef;

  public static final String SERIALIZED_NAME_OLD_TITLE = "old_title";
  @SerializedName(SERIALIZED_NAME_OLD_TITLE)
  @javax.annotation.Nullable
  private String oldTitle;

  public static final String SERIALIZED_NAME_PROJECT_ID = "project_id";
  @SerializedName(SERIALIZED_NAME_PROJECT_ID)
  @javax.annotation.Nullable
  private Long projectId;

  public static final String SERIALIZED_NAME_PULL_REQUEST_URL = "pull_request_url";
  @SerializedName(SERIALIZED_NAME_PULL_REQUEST_URL)
  @javax.annotation.Nullable
  private String pullRequestUrl;

  public static final String SERIALIZED_NAME_REF_ACTION = "ref_action";
  @SerializedName(SERIALIZED_NAME_REF_ACTION)
  @javax.annotation.Nullable
  private String refAction;

  public static final String SERIALIZED_NAME_REF_COMMENT = "ref_comment";
  @SerializedName(SERIALIZED_NAME_REF_COMMENT)
  @javax.annotation.Nullable
  private Comment refComment;

  public static final String SERIALIZED_NAME_REF_COMMIT_SHA = "ref_commit_sha";
  @SerializedName(SERIALIZED_NAME_REF_COMMIT_SHA)
  @javax.annotation.Nullable
  private String refCommitSha;

  public static final String SERIALIZED_NAME_REF_ISSUE = "ref_issue";
  @SerializedName(SERIALIZED_NAME_REF_ISSUE)
  @javax.annotation.Nullable
  private Issue refIssue;

  public static final String SERIALIZED_NAME_REMOVED_ASSIGNEE = "removed_assignee";
  @SerializedName(SERIALIZED_NAME_REMOVED_ASSIGNEE)
  @javax.annotation.Nullable
  private Boolean removedAssignee;

  public static final String SERIALIZED_NAME_RESOLVE_DOER = "resolve_doer";
  @SerializedName(SERIALIZED_NAME_RESOLVE_DOER)
  @javax.annotation.Nullable
  private User resolveDoer;

  public static final String SERIALIZED_NAME_REVIEW_ID = "review_id";
  @SerializedName(SERIALIZED_NAME_REVIEW_ID)
  @javax.annotation.Nullable
  private Long reviewId;

  public static final String SERIALIZED_NAME_TRACKED_TIME = "tracked_time";
  @SerializedName(SERIALIZED_NAME_TRACKED_TIME)
  @javax.annotation.Nullable
  private TrackedTime trackedTime;

  public static final String SERIALIZED_NAME_TYPE = "type";
  @SerializedName(SERIALIZED_NAME_TYPE)
  @javax.annotation.Nullable
  private String type;

  public static final String SERIALIZED_NAME_UPDATED_AT = "updated_at";
  @SerializedName(SERIALIZED_NAME_UPDATED_AT)
  @javax.annotation.Nullable
  private OffsetDateTime updatedAt;

  public static final String SERIALIZED_NAME_USER = "user";
  @SerializedName(SERIALIZED_NAME_USER)
  @javax.annotation.Nullable
  private User user;

  public TimelineComment() {
  }

  public TimelineComment assignee(@javax.annotation.Nullable User assignee) {
    this.assignee = assignee;
    return this;
  }

  /**
   * Get assignee
   * @return assignee
   */
  @javax.annotation.Nullable
  public User getAssignee() {
    return assignee;
  }

  public void setAssignee(@javax.annotation.Nullable User assignee) {
    this.assignee = assignee;
  }


  public TimelineComment assigneeTeam(@javax.annotation.Nullable Team assigneeTeam) {
    this.assigneeTeam = assigneeTeam;
    return this;
  }

  /**
   * Get assigneeTeam
   * @return assigneeTeam
   */
  @javax.annotation.Nullable
  public Team getAssigneeTeam() {
    return assigneeTeam;
  }

  public void setAssigneeTeam(@javax.annotation.Nullable Team assigneeTeam) {
    this.assigneeTeam = assigneeTeam;
  }


  public TimelineComment body(@javax.annotation.Nullable String body) {
    this.body = body;
    return this;
  }

  /**
   * Get body
   * @return body
   */
  @javax.annotation.Nullable
  public String getBody() {
    return body;
  }

  public void setBody(@javax.annotation.Nullable String body) {
    this.body = body;
  }


  public TimelineComment createdAt(@javax.annotation.Nullable OffsetDateTime createdAt) {
    this.createdAt = createdAt;
    return this;
  }

  /**
   * Get createdAt
   * @return createdAt
   */
  @javax.annotation.Nullable
  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }

  public void setCreatedAt(@javax.annotation.Nullable OffsetDateTime createdAt) {
    this.createdAt = createdAt;
  }


  public TimelineComment dependentIssue(@javax.annotation.Nullable Issue dependentIssue) {
    this.dependentIssue = dependentIssue;
    return this;
  }

  /**
   * Get dependentIssue
   * @return dependentIssue
   */
  @javax.annotation.Nullable
  public Issue getDependentIssue() {
    return dependentIssue;
  }

  public void setDependentIssue(@javax.annotation.Nullable Issue dependentIssue) {
    this.dependentIssue = dependentIssue;
  }


  public TimelineComment htmlUrl(@javax.annotation.Nullable String htmlUrl) {
    this.htmlUrl = htmlUrl;
    return this;
  }

  /**
   * Get htmlUrl
   * @return htmlUrl
   */
  @javax.annotation.Nullable
  public String getHtmlUrl() {
    return htmlUrl;
  }

  public void setHtmlUrl(@javax.annotation.Nullable String htmlUrl) {
    this.htmlUrl = htmlUrl;
  }


  public TimelineComment id(@javax.annotation.Nullable Long id) {
    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   */
  @javax.annotation.Nullable
  public Long getId() {
    return id;
  }

  public void setId(@javax.annotation.Nullable Long id) {
    this.id = id;
  }


  public TimelineComment issueUrl(@javax.annotation.Nullable String issueUrl) {
    this.issueUrl = issueUrl;
    return this;
  }

  /**
   * Get issueUrl
   * @return issueUrl
   */
  @javax.annotation.Nullable
  public String getIssueUrl() {
    return issueUrl;
  }

  public void setIssueUrl(@javax.annotation.Nullable String issueUrl) {
    this.issueUrl = issueUrl;
  }


  public TimelineComment label(@javax.annotation.Nullable Label label) {
    this.label = label;
    return this;
  }

  /**
   * Get label
   * @return label
   */
  @javax.annotation.Nullable
  public Label getLabel() {
    return label;
  }

  public void setLabel(@javax.annotation.Nullable Label label) {
    this.label = label;
  }


  public TimelineComment milestone(@javax.annotation.Nullable Milestone milestone) {
    this.milestone = milestone;
    return this;
  }

  /**
   * Get milestone
   * @return milestone
   */
  @javax.annotation.Nullable
  public Milestone getMilestone() {
    return milestone;
  }

  public void setMilestone(@javax.annotation.Nullable Milestone milestone) {
    this.milestone = milestone;
  }


  public TimelineComment newRef(@javax.annotation.Nullable String newRef) {
    this.newRef = newRef;
    return this;
  }

  /**
   * Get newRef
   * @return newRef
   */
  @javax.annotation.Nullable
  public String getNewRef() {
    return newRef;
  }

  public void setNewRef(@javax.annotation.Nullable String newRef) {
    this.newRef = newRef;
  }


  public TimelineComment newTitle(@javax.annotation.Nullable String newTitle) {
    this.newTitle = newTitle;
    return this;
  }

  /**
   * Get newTitle
   * @return newTitle
   */
  @javax.annotation.Nullable
  public String getNewTitle() {
    return newTitle;
  }

  public void setNewTitle(@javax.annotation.Nullable String newTitle) {
    this.newTitle = newTitle;
  }


  public TimelineComment oldMilestone(@javax.annotation.Nullable Milestone oldMilestone) {
    this.oldMilestone = oldMilestone;
    return this;
  }

  /**
   * Get oldMilestone
   * @return oldMilestone
   */
  @javax.annotation.Nullable
  public Milestone getOldMilestone() {
    return oldMilestone;
  }

  public void setOldMilestone(@javax.annotation.Nullable Milestone oldMilestone) {
    this.oldMilestone = oldMilestone;
  }


  public TimelineComment oldProjectId(@javax.annotation.Nullable Long oldProjectId) {
    this.oldProjectId = oldProjectId;
    return this;
  }

  /**
   * Get oldProjectId
   * @return oldProjectId
   */
  @javax.annotation.Nullable
  public Long getOldProjectId() {
    return oldProjectId;
  }

  public void setOldProjectId(@javax.annotation.Nullable Long oldProjectId) {
    this.oldProjectId = oldProjectId;
  }


  public TimelineComment oldRef(@javax.annotation.Nullable String oldRef) {
    this.oldRef = oldRef;
    return this;
  }

  /**
   * Get oldRef
   * @return oldRef
   */
  @javax.annotation.Nullable
  public String getOldRef() {
    return oldRef;
  }

  public void setOldRef(@javax.annotation.Nullable String oldRef) {
    this.oldRef = oldRef;
  }


  public TimelineComment oldTitle(@javax.annotation.Nullable String oldTitle) {
    this.oldTitle = oldTitle;
    return this;
  }

  /**
   * Get oldTitle
   * @return oldTitle
   */
  @javax.annotation.Nullable
  public String getOldTitle() {
    return oldTitle;
  }

  public void setOldTitle(@javax.annotation.Nullable String oldTitle) {
    this.oldTitle = oldTitle;
  }


  public TimelineComment projectId(@javax.annotation.Nullable Long projectId) {
    this.projectId = projectId;
    return this;
  }

  /**
   * Get projectId
   * @return projectId
   */
  @javax.annotation.Nullable
  public Long getProjectId() {
    return projectId;
  }

  public void setProjectId(@javax.annotation.Nullable Long projectId) {
    this.projectId = projectId;
  }


  public TimelineComment pullRequestUrl(@javax.annotation.Nullable String pullRequestUrl) {
    this.pullRequestUrl = pullRequestUrl;
    return this;
  }

  /**
   * Get pullRequestUrl
   * @return pullRequestUrl
   */
  @javax.annotation.Nullable
  public String getPullRequestUrl() {
    return pullRequestUrl;
  }

  public void setPullRequestUrl(@javax.annotation.Nullable String pullRequestUrl) {
    this.pullRequestUrl = pullRequestUrl;
  }


  public TimelineComment refAction(@javax.annotation.Nullable String refAction) {
    this.refAction = refAction;
    return this;
  }

  /**
   * Get refAction
   * @return refAction
   */
  @javax.annotation.Nullable
  public String getRefAction() {
    return refAction;
  }

  public void setRefAction(@javax.annotation.Nullable String refAction) {
    this.refAction = refAction;
  }


  public TimelineComment refComment(@javax.annotation.Nullable Comment refComment) {
    this.refComment = refComment;
    return this;
  }

  /**
   * Get refComment
   * @return refComment
   */
  @javax.annotation.Nullable
  public Comment getRefComment() {
    return refComment;
  }

  public void setRefComment(@javax.annotation.Nullable Comment refComment) {
    this.refComment = refComment;
  }


  public TimelineComment refCommitSha(@javax.annotation.Nullable String refCommitSha) {
    this.refCommitSha = refCommitSha;
    return this;
  }

  /**
   * commit SHA where issue/PR was referenced
   * @return refCommitSha
   */
  @javax.annotation.Nullable
  public String getRefCommitSha() {
    return refCommitSha;
  }

  public void setRefCommitSha(@javax.annotation.Nullable String refCommitSha) {
    this.refCommitSha = refCommitSha;
  }


  public TimelineComment refIssue(@javax.annotation.Nullable Issue refIssue) {
    this.refIssue = refIssue;
    return this;
  }

  /**
   * Get refIssue
   * @return refIssue
   */
  @javax.annotation.Nullable
  public Issue getRefIssue() {
    return refIssue;
  }

  public void setRefIssue(@javax.annotation.Nullable Issue refIssue) {
    this.refIssue = refIssue;
  }


  public TimelineComment removedAssignee(@javax.annotation.Nullable Boolean removedAssignee) {
    this.removedAssignee = removedAssignee;
    return this;
  }

  /**
   * whether the assignees were removed or added
   * @return removedAssignee
   */
  @javax.annotation.Nullable
  public Boolean getRemovedAssignee() {
    return removedAssignee;
  }

  public void setRemovedAssignee(@javax.annotation.Nullable Boolean removedAssignee) {
    this.removedAssignee = removedAssignee;
  }


  public TimelineComment resolveDoer(@javax.annotation.Nullable User resolveDoer) {
    this.resolveDoer = resolveDoer;
    return this;
  }

  /**
   * Get resolveDoer
   * @return resolveDoer
   */
  @javax.annotation.Nullable
  public User getResolveDoer() {
    return resolveDoer;
  }

  public void setResolveDoer(@javax.annotation.Nullable User resolveDoer) {
    this.resolveDoer = resolveDoer;
  }


  public TimelineComment reviewId(@javax.annotation.Nullable Long reviewId) {
    this.reviewId = reviewId;
    return this;
  }

  /**
   * Get reviewId
   * @return reviewId
   */
  @javax.annotation.Nullable
  public Long getReviewId() {
    return reviewId;
  }

  public void setReviewId(@javax.annotation.Nullable Long reviewId) {
    this.reviewId = reviewId;
  }


  public TimelineComment trackedTime(@javax.annotation.Nullable TrackedTime trackedTime) {
    this.trackedTime = trackedTime;
    return this;
  }

  /**
   * Get trackedTime
   * @return trackedTime
   */
  @javax.annotation.Nullable
  public TrackedTime getTrackedTime() {
    return trackedTime;
  }

  public void setTrackedTime(@javax.annotation.Nullable TrackedTime trackedTime) {
    this.trackedTime = trackedTime;
  }


  public TimelineComment type(@javax.annotation.Nullable String type) {
    this.type = type;
    return this;
  }

  /**
   * Get type
   * @return type
   */
  @javax.annotation.Nullable
  public String getType() {
    return type;
  }

  public void setType(@javax.annotation.Nullable String type) {
    this.type = type;
  }


  public TimelineComment updatedAt(@javax.annotation.Nullable OffsetDateTime updatedAt) {
    this.updatedAt = updatedAt;
    return this;
  }

  /**
   * Get updatedAt
   * @return updatedAt
   */
  @javax.annotation.Nullable
  public OffsetDateTime getUpdatedAt() {
    return updatedAt;
  }

  public void setUpdatedAt(@javax.annotation.Nullable OffsetDateTime updatedAt) {
    this.updatedAt = updatedAt;
  }


  public TimelineComment user(@javax.annotation.Nullable User user) {
    this.user = user;
    return this;
  }

  /**
   * Get user
   * @return user
   */
  @javax.annotation.Nullable
  public User getUser() {
    return user;
  }

  public void setUser(@javax.annotation.Nullable User user) {
    this.user = user;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TimelineComment timelineComment = (TimelineComment) o;
    return Objects.equals(this.assignee, timelineComment.assignee) &&
        Objects.equals(this.assigneeTeam, timelineComment.assigneeTeam) &&
        Objects.equals(this.body, timelineComment.body) &&
        Objects.equals(this.createdAt, timelineComment.createdAt) &&
        Objects.equals(this.dependentIssue, timelineComment.dependentIssue) &&
        Objects.equals(this.htmlUrl, timelineComment.htmlUrl) &&
        Objects.equals(this.id, timelineComment.id) &&
        Objects.equals(this.issueUrl, timelineComment.issueUrl) &&
        Objects.equals(this.label, timelineComment.label) &&
        Objects.equals(this.milestone, timelineComment.milestone) &&
        Objects.equals(this.newRef, timelineComment.newRef) &&
        Objects.equals(this.newTitle, timelineComment.newTitle) &&
        Objects.equals(this.oldMilestone, timelineComment.oldMilestone) &&
        Objects.equals(this.oldProjectId, timelineComment.oldProjectId) &&
        Objects.equals(this.oldRef, timelineComment.oldRef) &&
        Objects.equals(this.oldTitle, timelineComment.oldTitle) &&
        Objects.equals(this.projectId, timelineComment.projectId) &&
        Objects.equals(this.pullRequestUrl, timelineComment.pullRequestUrl) &&
        Objects.equals(this.refAction, timelineComment.refAction) &&
        Objects.equals(this.refComment, timelineComment.refComment) &&
        Objects.equals(this.refCommitSha, timelineComment.refCommitSha) &&
        Objects.equals(this.refIssue, timelineComment.refIssue) &&
        Objects.equals(this.removedAssignee, timelineComment.removedAssignee) &&
        Objects.equals(this.resolveDoer, timelineComment.resolveDoer) &&
        Objects.equals(this.reviewId, timelineComment.reviewId) &&
        Objects.equals(this.trackedTime, timelineComment.trackedTime) &&
        Objects.equals(this.type, timelineComment.type) &&
        Objects.equals(this.updatedAt, timelineComment.updatedAt) &&
        Objects.equals(this.user, timelineComment.user);
  }

  @Override
  public int hashCode() {
    return Objects.hash(assignee, assigneeTeam, body, createdAt, dependentIssue, htmlUrl, id, issueUrl, label, milestone, newRef, newTitle, oldMilestone, oldProjectId, oldRef, oldTitle, projectId, pullRequestUrl, refAction, refComment, refCommitSha, refIssue, removedAssignee, resolveDoer, reviewId, trackedTime, type, updatedAt, user);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TimelineComment {\n");
    sb.append("    assignee: ").append(toIndentedString(assignee)).append("\n");
    sb.append("    assigneeTeam: ").append(toIndentedString(assigneeTeam)).append("\n");
    sb.append("    body: ").append(toIndentedString(body)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    dependentIssue: ").append(toIndentedString(dependentIssue)).append("\n");
    sb.append("    htmlUrl: ").append(toIndentedString(htmlUrl)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    issueUrl: ").append(toIndentedString(issueUrl)).append("\n");
    sb.append("    label: ").append(toIndentedString(label)).append("\n");
    sb.append("    milestone: ").append(toIndentedString(milestone)).append("\n");
    sb.append("    newRef: ").append(toIndentedString(newRef)).append("\n");
    sb.append("    newTitle: ").append(toIndentedString(newTitle)).append("\n");
    sb.append("    oldMilestone: ").append(toIndentedString(oldMilestone)).append("\n");
    sb.append("    oldProjectId: ").append(toIndentedString(oldProjectId)).append("\n");
    sb.append("    oldRef: ").append(toIndentedString(oldRef)).append("\n");
    sb.append("    oldTitle: ").append(toIndentedString(oldTitle)).append("\n");
    sb.append("    projectId: ").append(toIndentedString(projectId)).append("\n");
    sb.append("    pullRequestUrl: ").append(toIndentedString(pullRequestUrl)).append("\n");
    sb.append("    refAction: ").append(toIndentedString(refAction)).append("\n");
    sb.append("    refComment: ").append(toIndentedString(refComment)).append("\n");
    sb.append("    refCommitSha: ").append(toIndentedString(refCommitSha)).append("\n");
    sb.append("    refIssue: ").append(toIndentedString(refIssue)).append("\n");
    sb.append("    removedAssignee: ").append(toIndentedString(removedAssignee)).append("\n");
    sb.append("    resolveDoer: ").append(toIndentedString(resolveDoer)).append("\n");
    sb.append("    reviewId: ").append(toIndentedString(reviewId)).append("\n");
    sb.append("    trackedTime: ").append(toIndentedString(trackedTime)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("    user: ").append(toIndentedString(user)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("assignee", "assignee_team", "body", "created_at", "dependent_issue", "html_url", "id", "issue_url", "label", "milestone", "new_ref", "new_title", "old_milestone", "old_project_id", "old_ref", "old_title", "project_id", "pull_request_url", "ref_action", "ref_comment", "ref_commit_sha", "ref_issue", "removed_assignee", "resolve_doer", "review_id", "tracked_time", "type", "updated_at", "user"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to TimelineComment
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!TimelineComment.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in TimelineComment is not found in the empty JSON string", TimelineComment.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!TimelineComment.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `TimelineComment` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the optional field `assignee`
      if (jsonObj.get("assignee") != null && !jsonObj.get("assignee").isJsonNull()) {
        User.validateJsonElement(jsonObj.get("assignee"));
      }
      // validate the optional field `assignee_team`
      if (jsonObj.get("assignee_team") != null && !jsonObj.get("assignee_team").isJsonNull()) {
        Team.validateJsonElement(jsonObj.get("assignee_team"));
      }
      if ((jsonObj.get("body") != null && !jsonObj.get("body").isJsonNull()) && !jsonObj.get("body").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `body` to be a primitive type in the JSON string but got `%s`", jsonObj.get("body").toString()));
      }
      // validate the optional field `dependent_issue`
      if (jsonObj.get("dependent_issue") != null && !jsonObj.get("dependent_issue").isJsonNull()) {
        Issue.validateJsonElement(jsonObj.get("dependent_issue"));
      }
      if ((jsonObj.get("html_url") != null && !jsonObj.get("html_url").isJsonNull()) && !jsonObj.get("html_url").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `html_url` to be a primitive type in the JSON string but got `%s`", jsonObj.get("html_url").toString()));
      }
      if ((jsonObj.get("issue_url") != null && !jsonObj.get("issue_url").isJsonNull()) && !jsonObj.get("issue_url").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `issue_url` to be a primitive type in the JSON string but got `%s`", jsonObj.get("issue_url").toString()));
      }
      // validate the optional field `label`
      if (jsonObj.get("label") != null && !jsonObj.get("label").isJsonNull()) {
        Label.validateJsonElement(jsonObj.get("label"));
      }
      // validate the optional field `milestone`
      if (jsonObj.get("milestone") != null && !jsonObj.get("milestone").isJsonNull()) {
        Milestone.validateJsonElement(jsonObj.get("milestone"));
      }
      if ((jsonObj.get("new_ref") != null && !jsonObj.get("new_ref").isJsonNull()) && !jsonObj.get("new_ref").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `new_ref` to be a primitive type in the JSON string but got `%s`", jsonObj.get("new_ref").toString()));
      }
      if ((jsonObj.get("new_title") != null && !jsonObj.get("new_title").isJsonNull()) && !jsonObj.get("new_title").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `new_title` to be a primitive type in the JSON string but got `%s`", jsonObj.get("new_title").toString()));
      }
      // validate the optional field `old_milestone`
      if (jsonObj.get("old_milestone") != null && !jsonObj.get("old_milestone").isJsonNull()) {
        Milestone.validateJsonElement(jsonObj.get("old_milestone"));
      }
      if ((jsonObj.get("old_ref") != null && !jsonObj.get("old_ref").isJsonNull()) && !jsonObj.get("old_ref").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `old_ref` to be a primitive type in the JSON string but got `%s`", jsonObj.get("old_ref").toString()));
      }
      if ((jsonObj.get("old_title") != null && !jsonObj.get("old_title").isJsonNull()) && !jsonObj.get("old_title").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `old_title` to be a primitive type in the JSON string but got `%s`", jsonObj.get("old_title").toString()));
      }
      if ((jsonObj.get("pull_request_url") != null && !jsonObj.get("pull_request_url").isJsonNull()) && !jsonObj.get("pull_request_url").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `pull_request_url` to be a primitive type in the JSON string but got `%s`", jsonObj.get("pull_request_url").toString()));
      }
      if ((jsonObj.get("ref_action") != null && !jsonObj.get("ref_action").isJsonNull()) && !jsonObj.get("ref_action").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `ref_action` to be a primitive type in the JSON string but got `%s`", jsonObj.get("ref_action").toString()));
      }
      // validate the optional field `ref_comment`
      if (jsonObj.get("ref_comment") != null && !jsonObj.get("ref_comment").isJsonNull()) {
        Comment.validateJsonElement(jsonObj.get("ref_comment"));
      }
      if ((jsonObj.get("ref_commit_sha") != null && !jsonObj.get("ref_commit_sha").isJsonNull()) && !jsonObj.get("ref_commit_sha").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `ref_commit_sha` to be a primitive type in the JSON string but got `%s`", jsonObj.get("ref_commit_sha").toString()));
      }
      // validate the optional field `ref_issue`
      if (jsonObj.get("ref_issue") != null && !jsonObj.get("ref_issue").isJsonNull()) {
        Issue.validateJsonElement(jsonObj.get("ref_issue"));
      }
      // validate the optional field `resolve_doer`
      if (jsonObj.get("resolve_doer") != null && !jsonObj.get("resolve_doer").isJsonNull()) {
        User.validateJsonElement(jsonObj.get("resolve_doer"));
      }
      // validate the optional field `tracked_time`
      if (jsonObj.get("tracked_time") != null && !jsonObj.get("tracked_time").isJsonNull()) {
        TrackedTime.validateJsonElement(jsonObj.get("tracked_time"));
      }
      if ((jsonObj.get("type") != null && !jsonObj.get("type").isJsonNull()) && !jsonObj.get("type").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `type` to be a primitive type in the JSON string but got `%s`", jsonObj.get("type").toString()));
      }
      // validate the optional field `user`
      if (jsonObj.get("user") != null && !jsonObj.get("user").isJsonNull()) {
        User.validateJsonElement(jsonObj.get("user"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!TimelineComment.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'TimelineComment' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<TimelineComment> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(TimelineComment.class));

       return (TypeAdapter<T>) new TypeAdapter<TimelineComment>() {
           @Override
           public void write(JsonWriter out, TimelineComment value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public TimelineComment read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of TimelineComment given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of TimelineComment
   * @throws IOException if the JSON string is invalid with respect to TimelineComment
   */
  public static TimelineComment fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, TimelineComment.class);
  }

  /**
   * Convert an instance of TimelineComment to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

