/*
 * Forgejo API
 * This documentation describes the Forgejo API.
 *
 * The version of the OpenAPI document: 14.0.3+gitea-1.22.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.smithyai.forgejoclient.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import dev.smithyai.forgejoclient.model.CommitDateOptions;
import dev.smithyai.forgejoclient.model.Identity;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import dev.smithyai.forgejoclient.JSON;

/**
 * UpdateFileOptions options for updating files Note: &#x60;author&#x60; and &#x60;committer&#x60; are optional (if only one is given, it will be used for the other, otherwise the authenticated user will be used)
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-03-09T21:54:47.594851+01:00[Europe/Amsterdam]", comments = "Generator version: 7.20.0")
public class UpdateFileOptions {
  public static final String SERIALIZED_NAME_AUTHOR = "author";
  @SerializedName(SERIALIZED_NAME_AUTHOR)
  @javax.annotation.Nullable
  private Identity author;

  public static final String SERIALIZED_NAME_BRANCH = "branch";
  @SerializedName(SERIALIZED_NAME_BRANCH)
  @javax.annotation.Nullable
  private String branch;

  public static final String SERIALIZED_NAME_COMMITTER = "committer";
  @SerializedName(SERIALIZED_NAME_COMMITTER)
  @javax.annotation.Nullable
  private Identity committer;

  public static final String SERIALIZED_NAME_CONTENT = "content";
  @SerializedName(SERIALIZED_NAME_CONTENT)
  @javax.annotation.Nonnull
  private String content;

  public static final String SERIALIZED_NAME_DATES = "dates";
  @SerializedName(SERIALIZED_NAME_DATES)
  @javax.annotation.Nullable
  private CommitDateOptions dates;

  public static final String SERIALIZED_NAME_FROM_PATH = "from_path";
  @SerializedName(SERIALIZED_NAME_FROM_PATH)
  @javax.annotation.Nullable
  private String fromPath;

  public static final String SERIALIZED_NAME_MESSAGE = "message";
  @SerializedName(SERIALIZED_NAME_MESSAGE)
  @javax.annotation.Nullable
  private String message;

  public static final String SERIALIZED_NAME_NEW_BRANCH = "new_branch";
  @SerializedName(SERIALIZED_NAME_NEW_BRANCH)
  @javax.annotation.Nullable
  private String newBranch;

  public static final String SERIALIZED_NAME_SHA = "sha";
  @SerializedName(SERIALIZED_NAME_SHA)
  @javax.annotation.Nonnull
  private String sha;

  public static final String SERIALIZED_NAME_SIGNOFF = "signoff";
  @SerializedName(SERIALIZED_NAME_SIGNOFF)
  @javax.annotation.Nullable
  private Boolean signoff;

  public UpdateFileOptions() {
  }

  public UpdateFileOptions author(@javax.annotation.Nullable Identity author) {
    this.author = author;
    return this;
  }

  /**
   * Get author
   * @return author
   */
  @javax.annotation.Nullable
  public Identity getAuthor() {
    return author;
  }

  public void setAuthor(@javax.annotation.Nullable Identity author) {
    this.author = author;
  }


  public UpdateFileOptions branch(@javax.annotation.Nullable String branch) {
    this.branch = branch;
    return this;
  }

  /**
   * branch (optional) to base this file from. if not given, the default branch is used
   * @return branch
   */
  @javax.annotation.Nullable
  public String getBranch() {
    return branch;
  }

  public void setBranch(@javax.annotation.Nullable String branch) {
    this.branch = branch;
  }


  public UpdateFileOptions committer(@javax.annotation.Nullable Identity committer) {
    this.committer = committer;
    return this;
  }

  /**
   * Get committer
   * @return committer
   */
  @javax.annotation.Nullable
  public Identity getCommitter() {
    return committer;
  }

  public void setCommitter(@javax.annotation.Nullable Identity committer) {
    this.committer = committer;
  }


  public UpdateFileOptions content(@javax.annotation.Nonnull String content) {
    this.content = content;
    return this;
  }

  /**
   * content must be base64 encoded
   * @return content
   */
  @javax.annotation.Nonnull
  public String getContent() {
    return content;
  }

  public void setContent(@javax.annotation.Nonnull String content) {
    this.content = content;
  }


  public UpdateFileOptions dates(@javax.annotation.Nullable CommitDateOptions dates) {
    this.dates = dates;
    return this;
  }

  /**
   * Get dates
   * @return dates
   */
  @javax.annotation.Nullable
  public CommitDateOptions getDates() {
    return dates;
  }

  public void setDates(@javax.annotation.Nullable CommitDateOptions dates) {
    this.dates = dates;
  }


  public UpdateFileOptions fromPath(@javax.annotation.Nullable String fromPath) {
    this.fromPath = fromPath;
    return this;
  }

  /**
   * from_path (optional) is the path of the original file which will be moved/renamed to the path in the URL
   * @return fromPath
   */
  @javax.annotation.Nullable
  public String getFromPath() {
    return fromPath;
  }

  public void setFromPath(@javax.annotation.Nullable String fromPath) {
    this.fromPath = fromPath;
  }


  public UpdateFileOptions message(@javax.annotation.Nullable String message) {
    this.message = message;
    return this;
  }

  /**
   * message (optional) for the commit of this file. if not supplied, a default message will be used
   * @return message
   */
  @javax.annotation.Nullable
  public String getMessage() {
    return message;
  }

  public void setMessage(@javax.annotation.Nullable String message) {
    this.message = message;
  }


  public UpdateFileOptions newBranch(@javax.annotation.Nullable String newBranch) {
    this.newBranch = newBranch;
    return this;
  }

  /**
   * new_branch (optional) will make a new branch from &#x60;branch&#x60; before creating the file
   * @return newBranch
   */
  @javax.annotation.Nullable
  public String getNewBranch() {
    return newBranch;
  }

  public void setNewBranch(@javax.annotation.Nullable String newBranch) {
    this.newBranch = newBranch;
  }


  public UpdateFileOptions sha(@javax.annotation.Nonnull String sha) {
    this.sha = sha;
    return this;
  }

  /**
   * sha is the SHA for the file that already exists
   * @return sha
   */
  @javax.annotation.Nonnull
  public String getSha() {
    return sha;
  }

  public void setSha(@javax.annotation.Nonnull String sha) {
    this.sha = sha;
  }


  public UpdateFileOptions signoff(@javax.annotation.Nullable Boolean signoff) {
    this.signoff = signoff;
    return this;
  }

  /**
   * Add a Signed-off-by trailer by the committer at the end of the commit log message.
   * @return signoff
   */
  @javax.annotation.Nullable
  public Boolean getSignoff() {
    return signoff;
  }

  public void setSignoff(@javax.annotation.Nullable Boolean signoff) {
    this.signoff = signoff;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the UpdateFileOptions instance itself
   */
  public UpdateFileOptions putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UpdateFileOptions updateFileOptions = (UpdateFileOptions) o;
    return Objects.equals(this.author, updateFileOptions.author) &&
        Objects.equals(this.branch, updateFileOptions.branch) &&
        Objects.equals(this.committer, updateFileOptions.committer) &&
        Objects.equals(this.content, updateFileOptions.content) &&
        Objects.equals(this.dates, updateFileOptions.dates) &&
        Objects.equals(this.fromPath, updateFileOptions.fromPath) &&
        Objects.equals(this.message, updateFileOptions.message) &&
        Objects.equals(this.newBranch, updateFileOptions.newBranch) &&
        Objects.equals(this.sha, updateFileOptions.sha) &&
        Objects.equals(this.signoff, updateFileOptions.signoff)&&
        Objects.equals(this.additionalProperties, updateFileOptions.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(author, branch, committer, content, dates, fromPath, message, newBranch, sha, signoff, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UpdateFileOptions {\n");
    sb.append("    author: ").append(toIndentedString(author)).append("\n");
    sb.append("    branch: ").append(toIndentedString(branch)).append("\n");
    sb.append("    committer: ").append(toIndentedString(committer)).append("\n");
    sb.append("    content: ").append(toIndentedString(content)).append("\n");
    sb.append("    dates: ").append(toIndentedString(dates)).append("\n");
    sb.append("    fromPath: ").append(toIndentedString(fromPath)).append("\n");
    sb.append("    message: ").append(toIndentedString(message)).append("\n");
    sb.append("    newBranch: ").append(toIndentedString(newBranch)).append("\n");
    sb.append("    sha: ").append(toIndentedString(sha)).append("\n");
    sb.append("    signoff: ").append(toIndentedString(signoff)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("author", "branch", "committer", "content", "dates", "from_path", "message", "new_branch", "sha", "signoff"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("content", "sha"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to UpdateFileOptions
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!UpdateFileOptions.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in UpdateFileOptions is not found in the empty JSON string", UpdateFileOptions.openapiRequiredFields.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : UpdateFileOptions.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the optional field `author`
      if (jsonObj.get("author") != null && !jsonObj.get("author").isJsonNull()) {
        Identity.validateJsonElement(jsonObj.get("author"));
      }
      if ((jsonObj.get("branch") != null && !jsonObj.get("branch").isJsonNull()) && !jsonObj.get("branch").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `branch` to be a primitive type in the JSON string but got `%s`", jsonObj.get("branch").toString()));
      }
      // validate the optional field `committer`
      if (jsonObj.get("committer") != null && !jsonObj.get("committer").isJsonNull()) {
        Identity.validateJsonElement(jsonObj.get("committer"));
      }
      if (!jsonObj.get("content").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `content` to be a primitive type in the JSON string but got `%s`", jsonObj.get("content").toString()));
      }
      // validate the optional field `dates`
      if (jsonObj.get("dates") != null && !jsonObj.get("dates").isJsonNull()) {
        CommitDateOptions.validateJsonElement(jsonObj.get("dates"));
      }
      if ((jsonObj.get("from_path") != null && !jsonObj.get("from_path").isJsonNull()) && !jsonObj.get("from_path").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `from_path` to be a primitive type in the JSON string but got `%s`", jsonObj.get("from_path").toString()));
      }
      if ((jsonObj.get("message") != null && !jsonObj.get("message").isJsonNull()) && !jsonObj.get("message").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `message` to be a primitive type in the JSON string but got `%s`", jsonObj.get("message").toString()));
      }
      if ((jsonObj.get("new_branch") != null && !jsonObj.get("new_branch").isJsonNull()) && !jsonObj.get("new_branch").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `new_branch` to be a primitive type in the JSON string but got `%s`", jsonObj.get("new_branch").toString()));
      }
      if (!jsonObj.get("sha").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `sha` to be a primitive type in the JSON string but got `%s`", jsonObj.get("sha").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!UpdateFileOptions.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'UpdateFileOptions' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<UpdateFileOptions> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(UpdateFileOptions.class));

       return (TypeAdapter<T>) new TypeAdapter<UpdateFileOptions>() {
           @Override
           public void write(JsonWriter out, UpdateFileOptions value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additional properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   JsonElement jsonElement = gson.toJsonTree(entry.getValue());
                   if (jsonElement.isJsonArray()) {
                     obj.add(entry.getKey(), jsonElement.getAsJsonArray());
                   } else {
                     obj.add(entry.getKey(), jsonElement.getAsJsonObject());
                   }
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public UpdateFileOptions read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             JsonObject jsonObj = jsonElement.getAsJsonObject();
             // store additional fields in the deserialized instance
             UpdateFileOptions instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of UpdateFileOptions given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of UpdateFileOptions
   * @throws IOException if the JSON string is invalid with respect to UpdateFileOptions
   */
  public static UpdateFileOptions fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, UpdateFileOptions.class);
  }

  /**
   * Convert an instance of UpdateFileOptions to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

